export const pageRoutes={
  dashboard:"/dashboard",
  sales:"/sales",
  pos:"/pos",
  orders:"/orders",
  diningRoom:"/dining-room",
  kitchen:"/kitchen",
  tables:"/tables",
  cash:"/cash",
  reservations:"/reservations",
  callCenter:"/call-center",
  qrMenu:"/qr-menu",
  kiosk:"/kiosk",
  products:"/products",
  availability:"/availability",
  combos:"/combos",
  recipes:"/recipes",
  inventory:"/inventory",
  stockLedger:"/stock-ledger",
  purchases:"/purchases",
  logistics:"/logistics",
  delivery:"/delivery",
  deliveryApps:"/delivery-apps",
  couriers:"/couriers",
  customers:"/customers",
  crm:"/crm",
  loyaltyPoints:"/loyalty-points",
  offers:"/offers",
  staff:"/staff",
  locations:"/locations",
  expenses:"/expenses",
  businessIntelligence:"/bi",
  appManager:"/app-manager",
  settings:"/settings",
  gettingStarted:"/settings/getting-started",
  organizationSettings:"/settings/organization",
  taxSettings:"/settings/tax",
  paymentMethods:"/settings/payment-methods",
  usersSettings:"/settings/users",
  billingSettings:"/settings/billing",
  modulesSettings:"/settings/modules",
  integrationsSettings:"/settings/integrations",
  operationsSettings:"/settings/operations",
  profileSettings:"/settings/profile",
  concierge:"/whatsapp-bot",
  receipts:"/receipts",
  noAccess:"/no-access",
  publicConcierge:"/api/public/concierge/:qr",
  publicTable:"/table/:qr",
  platformOnboarding:"/platform/onboarding",
  platformPlans:"/platform/plans",
  platformSubscription:"/platform/subscription",
  platformGlobalSettings:"/platform/configuracion-global",
  login:"/login",
} as const;

export const legacyPageAliases=[
  {legacy:"/ventas",canonical:pageRoutes.sales},
  {legacy:"/pedidos",canonical:pageRoutes.orders},
  {legacy:"/salon",canonical:pageRoutes.diningRoom},
  {legacy:"/cocina",canonical:pageRoutes.kitchen},
  {legacy:"/mesas",canonical:pageRoutes.tables},
  {legacy:"/caja",canonical:pageRoutes.cash},
  {legacy:"/reservas",canonical:pageRoutes.reservations},
  {legacy:"/carta-qr",canonical:pageRoutes.qrMenu},
  {legacy:"/kiosco",canonical:pageRoutes.kiosk},
  {legacy:"/productos",canonical:pageRoutes.products},
  {legacy:"/disponibilidad",canonical:pageRoutes.availability},
  {legacy:"/recetas",canonical:pageRoutes.recipes},
  {legacy:"/inventario",canonical:pageRoutes.inventory},
  {legacy:"/kardex",canonical:pageRoutes.stockLedger},
  {legacy:"/compras",canonical:pageRoutes.purchases},
  {legacy:"/logistica",canonical:pageRoutes.logistics},
  {legacy:"/repartidores",canonical:pageRoutes.couriers},
  {legacy:"/clientes",canonical:pageRoutes.customers},
  {legacy:"/puntos",canonical:pageRoutes.loyaltyPoints},
  {legacy:"/ofertas",canonical:pageRoutes.offers},
  {legacy:"/personal",canonical:pageRoutes.staff},
  {legacy:"/locales",canonical:pageRoutes.locations},
  {legacy:"/costos",canonical:pageRoutes.expenses},
  {legacy:"/configuracion",canonical:pageRoutes.settings},
  {legacy:"/configuracion/puesta-en-marcha",canonical:pageRoutes.gettingStarted},
  {legacy:"/configuracion/empresa",canonical:pageRoutes.organizationSettings},
  {legacy:"/configuracion/fiscal",canonical:pageRoutes.taxSettings},
  {legacy:"/configuracion/medios-pago",canonical:pageRoutes.paymentMethods},
  {legacy:"/configuracion/usuarios",canonical:pageRoutes.usersSettings},
  {legacy:"/configuracion/facturacion",canonical:pageRoutes.billingSettings},
  {legacy:"/configuracion/modulos",canonical:pageRoutes.modulesSettings},
  {legacy:"/configuracion/integraciones",canonical:pageRoutes.integrationsSettings},
  {legacy:"/configuracion/operacion",canonical:pageRoutes.operationsSettings},
  {legacy:"/configuracion/perfil",canonical:pageRoutes.profileSettings},
  {legacy:"/sin-acceso",canonical:pageRoutes.noAccess},
  {legacy:"/comprobantes",canonical:pageRoutes.receipts},
  {legacy:"/mesa/:qr",canonical:pageRoutes.publicTable},
] as const;

export const legacyPageRedirects=[
  ...legacyPageAliases,
  {legacy:"/configuracion/onboarding",canonical:pageRoutes.platformOnboarding},
] as const;

export function publicConciergePath(qr:string){
  return pageRoutes.publicConcierge.replace(":qr",encodeURIComponent(qr));
}
