// Code generated from Unicode CLDR main; DO NOT EDIT.
package httpapi

type countryOption struct {
	Code            string `json:"code"`
	Name            string `json:"name"`
	DefaultCurrency string `json:"defaultCurrency"`
}

var supportedCountries = []countryOption{
	{Code: "AF", Name: "Afganistán", DefaultCurrency: "AFN"},
	{Code: "AL", Name: "Albania", DefaultCurrency: "ALL"},
	{Code: "DE", Name: "Alemania", DefaultCurrency: "EUR"},
	{Code: "AD", Name: "Andorra", DefaultCurrency: "EUR"},
	{Code: "AO", Name: "Angola", DefaultCurrency: "AOA"},
	{Code: "AI", Name: "Anguila", DefaultCurrency: "XCD"},
	{Code: "AG", Name: "Antigua y Barbuda", DefaultCurrency: "XCD"},
	{Code: "SA", Name: "Arabia Saudí", DefaultCurrency: "SAR"},
	{Code: "DZ", Name: "Argelia", DefaultCurrency: "DZD"},
	{Code: "AR", Name: "Argentina", DefaultCurrency: "ARS"},
	{Code: "AM", Name: "Armenia", DefaultCurrency: "AMD"},
	{Code: "AW", Name: "Aruba", DefaultCurrency: "AWG"},
	{Code: "AU", Name: "Australia", DefaultCurrency: "AUD"},
	{Code: "AT", Name: "Austria", DefaultCurrency: "EUR"},
	{Code: "AZ", Name: "Azerbaiyán", DefaultCurrency: "AZN"},
	{Code: "BS", Name: "Bahamas", DefaultCurrency: "BSD"},
	{Code: "BD", Name: "Bangladés", DefaultCurrency: "BDT"},
	{Code: "BB", Name: "Barbados", DefaultCurrency: "BBD"},
	{Code: "BH", Name: "Baréin", DefaultCurrency: "BHD"},
	{Code: "BE", Name: "Bélgica", DefaultCurrency: "EUR"},
	{Code: "BZ", Name: "Belice", DefaultCurrency: "BZD"},
	{Code: "BJ", Name: "Benín", DefaultCurrency: "XOF"},
	{Code: "BM", Name: "Bermudas", DefaultCurrency: "BMD"},
	{Code: "BY", Name: "Bielorrusia", DefaultCurrency: "BYN"},
	{Code: "BO", Name: "Bolivia", DefaultCurrency: "BOB"},
	{Code: "BA", Name: "Bosnia y Herzegovina", DefaultCurrency: "BAM"},
	{Code: "BW", Name: "Botsuana", DefaultCurrency: "BWP"},
	{Code: "BR", Name: "Brasil", DefaultCurrency: "BRL"},
	{Code: "BN", Name: "Brunéi", DefaultCurrency: "BND"},
	{Code: "BG", Name: "Bulgaria", DefaultCurrency: "EUR"},
	{Code: "BF", Name: "Burkina Faso", DefaultCurrency: "XOF"},
	{Code: "BI", Name: "Burundi", DefaultCurrency: "BIF"},
	{Code: "BT", Name: "Bután", DefaultCurrency: "BTN"},
	{Code: "CV", Name: "Cabo Verde", DefaultCurrency: "CVE"},
	{Code: "KH", Name: "Camboya", DefaultCurrency: "KHR"},
	{Code: "CM", Name: "Camerún", DefaultCurrency: "XAF"},
	{Code: "CA", Name: "Canadá", DefaultCurrency: "CAD"},
	{Code: "IC", Name: "Canarias", DefaultCurrency: "EUR"},
	{Code: "BQ", Name: "Caribe neerlandés", DefaultCurrency: "USD"},
	{Code: "QA", Name: "Catar", DefaultCurrency: "QAR"},
	{Code: "EA", Name: "Ceuta y Melilla", DefaultCurrency: "EUR"},
	{Code: "TD", Name: "Chad", DefaultCurrency: "XAF"},
	{Code: "CZ", Name: "Chequia", DefaultCurrency: "CZK"},
	{Code: "CL", Name: "Chile", DefaultCurrency: "CLP"},
	{Code: "CN", Name: "China", DefaultCurrency: "CNY"},
	{Code: "CY", Name: "Chipre", DefaultCurrency: "EUR"},
	{Code: "VA", Name: "Ciudad del Vaticano", DefaultCurrency: "EUR"},
	{Code: "CO", Name: "Colombia", DefaultCurrency: "COP"},
	{Code: "KM", Name: "Comoras", DefaultCurrency: "KMF"},
	{Code: "CG", Name: "Congo", DefaultCurrency: "XAF"},
	{Code: "KP", Name: "Corea del Norte", DefaultCurrency: "KPW"},
	{Code: "KR", Name: "Corea del Sur", DefaultCurrency: "KRW"},
	{Code: "CR", Name: "Costa Rica", DefaultCurrency: "CRC"},
	{Code: "CI", Name: "Côte d’Ivoire", DefaultCurrency: "XOF"},
	{Code: "HR", Name: "Croacia", DefaultCurrency: "EUR"},
	{Code: "CU", Name: "Cuba", DefaultCurrency: "CUP"},
	{Code: "CW", Name: "Curazao", DefaultCurrency: "XCG"},
	{Code: "DG", Name: "Diego García", DefaultCurrency: "USD"},
	{Code: "DK", Name: "Dinamarca", DefaultCurrency: "DKK"},
	{Code: "DM", Name: "Dominica", DefaultCurrency: "XCD"},
	{Code: "EC", Name: "Ecuador", DefaultCurrency: "USD"},
	{Code: "EG", Name: "Egipto", DefaultCurrency: "EGP"},
	{Code: "SV", Name: "El Salvador", DefaultCurrency: "USD"},
	{Code: "AE", Name: "Emiratos Árabes Unidos", DefaultCurrency: "AED"},
	{Code: "ER", Name: "Eritrea", DefaultCurrency: "ERN"},
	{Code: "SK", Name: "Eslovaquia", DefaultCurrency: "EUR"},
	{Code: "SI", Name: "Eslovenia", DefaultCurrency: "EUR"},
	{Code: "ES", Name: "España", DefaultCurrency: "EUR"},
	{Code: "US", Name: "Estados Unidos", DefaultCurrency: "USD"},
	{Code: "EE", Name: "Estonia", DefaultCurrency: "EUR"},
	{Code: "SZ", Name: "Esuatini", DefaultCurrency: "SZL"},
	{Code: "ET", Name: "Etiopía", DefaultCurrency: "ETB"},
	{Code: "PH", Name: "Filipinas", DefaultCurrency: "PHP"},
	{Code: "FI", Name: "Finlandia", DefaultCurrency: "EUR"},
	{Code: "FJ", Name: "Fiyi", DefaultCurrency: "FJD"},
	{Code: "FR", Name: "Francia", DefaultCurrency: "EUR"},
	{Code: "GA", Name: "Gabón", DefaultCurrency: "XAF"},
	{Code: "GM", Name: "Gambia", DefaultCurrency: "GMD"},
	{Code: "GE", Name: "Georgia", DefaultCurrency: "GEL"},
	{Code: "GH", Name: "Ghana", DefaultCurrency: "GHS"},
	{Code: "GI", Name: "Gibraltar", DefaultCurrency: "GIP"},
	{Code: "GD", Name: "Granada", DefaultCurrency: "XCD"},
	{Code: "GR", Name: "Grecia", DefaultCurrency: "EUR"},
	{Code: "GL", Name: "Groenlandia", DefaultCurrency: "DKK"},
	{Code: "GP", Name: "Guadalupe", DefaultCurrency: "EUR"},
	{Code: "GU", Name: "Guam", DefaultCurrency: "USD"},
	{Code: "GT", Name: "Guatemala", DefaultCurrency: "GTQ"},
	{Code: "GF", Name: "Guayana Francesa", DefaultCurrency: "EUR"},
	{Code: "GG", Name: "Guernesey", DefaultCurrency: "GBP"},
	{Code: "GN", Name: "Guinea", DefaultCurrency: "GNF"},
	{Code: "GQ", Name: "Guinea Ecuatorial", DefaultCurrency: "XAF"},
	{Code: "GW", Name: "Guinea-Bisáu", DefaultCurrency: "XOF"},
	{Code: "GY", Name: "Guyana", DefaultCurrency: "GYD"},
	{Code: "HT", Name: "Haití", DefaultCurrency: "HTG"},
	{Code: "HN", Name: "Honduras", DefaultCurrency: "HNL"},
	{Code: "HU", Name: "Hungría", DefaultCurrency: "HUF"},
	{Code: "IN", Name: "India", DefaultCurrency: "INR"},
	{Code: "ID", Name: "Indonesia", DefaultCurrency: "IDR"},
	{Code: "IQ", Name: "Irak", DefaultCurrency: "IQD"},
	{Code: "IR", Name: "Irán", DefaultCurrency: "IRR"},
	{Code: "IE", Name: "Irlanda", DefaultCurrency: "EUR"},
	{Code: "BV", Name: "Isla Bouvet", DefaultCurrency: "NOK"},
	{Code: "AC", Name: "Isla de la Ascensión", DefaultCurrency: "SHP"},
	{Code: "IM", Name: "Isla de Man", DefaultCurrency: "GBP"},
	{Code: "CX", Name: "Isla de Navidad", DefaultCurrency: "AUD"},
	{Code: "NF", Name: "Isla Norfolk", DefaultCurrency: "AUD"},
	{Code: "IS", Name: "Islandia", DefaultCurrency: "ISK"},
	{Code: "AX", Name: "Islas Aland", DefaultCurrency: "EUR"},
	{Code: "KY", Name: "Islas Caimán", DefaultCurrency: "KYD"},
	{Code: "CC", Name: "Islas Cocos", DefaultCurrency: "AUD"},
	{Code: "CK", Name: "Islas Cook", DefaultCurrency: "NZD"},
	{Code: "FO", Name: "Islas Feroe", DefaultCurrency: "DKK"},
	{Code: "GS", Name: "Islas Georgia del Sur y Sandwich del Sur", DefaultCurrency: "GBP"},
	{Code: "HM", Name: "Islas Heard y McDonald", DefaultCurrency: "AUD"},
	{Code: "FK", Name: "Islas Malvinas", DefaultCurrency: "FKP"},
	{Code: "MP", Name: "Islas Marianas del Norte", DefaultCurrency: "USD"},
	{Code: "MH", Name: "Islas Marshall", DefaultCurrency: "USD"},
	{Code: "UM", Name: "Islas menores alejadas de EE. UU.", DefaultCurrency: "USD"},
	{Code: "PN", Name: "Islas Pitcairn", DefaultCurrency: "NZD"},
	{Code: "SB", Name: "Islas Salomón", DefaultCurrency: "SBD"},
	{Code: "TC", Name: "Islas Turcas y Caicos", DefaultCurrency: "USD"},
	{Code: "VG", Name: "Islas Vírgenes Británicas", DefaultCurrency: "USD"},
	{Code: "VI", Name: "Islas Vírgenes de EE. UU.", DefaultCurrency: "USD"},
	{Code: "IL", Name: "Israel", DefaultCurrency: "ILS"},
	{Code: "IT", Name: "Italia", DefaultCurrency: "EUR"},
	{Code: "JM", Name: "Jamaica", DefaultCurrency: "JMD"},
	{Code: "JP", Name: "Japón", DefaultCurrency: "JPY"},
	{Code: "JE", Name: "Jersey", DefaultCurrency: "GBP"},
	{Code: "JO", Name: "Jordania", DefaultCurrency: "JOD"},
	{Code: "KZ", Name: "Kazajistán", DefaultCurrency: "KZT"},
	{Code: "KE", Name: "Kenia", DefaultCurrency: "KES"},
	{Code: "KG", Name: "Kirguistán", DefaultCurrency: "KGS"},
	{Code: "KI", Name: "Kiribati", DefaultCurrency: "AUD"},
	{Code: "XK", Name: "Kosovo", DefaultCurrency: "EUR"},
	{Code: "KW", Name: "Kuwait", DefaultCurrency: "KWD"},
	{Code: "LA", Name: "Laos", DefaultCurrency: "LAK"},
	{Code: "LS", Name: "Lesoto", DefaultCurrency: "ZAR"},
	{Code: "LV", Name: "Letonia", DefaultCurrency: "EUR"},
	{Code: "LB", Name: "Líbano", DefaultCurrency: "LBP"},
	{Code: "LR", Name: "Liberia", DefaultCurrency: "LRD"},
	{Code: "LY", Name: "Libia", DefaultCurrency: "LYD"},
	{Code: "LI", Name: "Liechtenstein", DefaultCurrency: "CHF"},
	{Code: "LT", Name: "Lituania", DefaultCurrency: "EUR"},
	{Code: "LU", Name: "Luxemburgo", DefaultCurrency: "EUR"},
	{Code: "MK", Name: "Macedonia del Norte", DefaultCurrency: "MKD"},
	{Code: "MG", Name: "Madagascar", DefaultCurrency: "MGA"},
	{Code: "MY", Name: "Malasia", DefaultCurrency: "MYR"},
	{Code: "MW", Name: "Malaui", DefaultCurrency: "MWK"},
	{Code: "MV", Name: "Maldivas", DefaultCurrency: "MVR"},
	{Code: "ML", Name: "Mali", DefaultCurrency: "XOF"},
	{Code: "MT", Name: "Malta", DefaultCurrency: "EUR"},
	{Code: "MA", Name: "Marruecos", DefaultCurrency: "MAD"},
	{Code: "MQ", Name: "Martinica", DefaultCurrency: "EUR"},
	{Code: "MU", Name: "Mauricio", DefaultCurrency: "MUR"},
	{Code: "MR", Name: "Mauritania", DefaultCurrency: "MRU"},
	{Code: "YT", Name: "Mayotte", DefaultCurrency: "EUR"},
	{Code: "MX", Name: "México", DefaultCurrency: "MXN"},
	{Code: "FM", Name: "Micronesia", DefaultCurrency: "USD"},
	{Code: "MD", Name: "Moldavia", DefaultCurrency: "MDL"},
	{Code: "MC", Name: "Mónaco", DefaultCurrency: "EUR"},
	{Code: "MN", Name: "Mongolia", DefaultCurrency: "MNT"},
	{Code: "ME", Name: "Montenegro", DefaultCurrency: "EUR"},
	{Code: "MS", Name: "Montserrat", DefaultCurrency: "XCD"},
	{Code: "MZ", Name: "Mozambique", DefaultCurrency: "MZN"},
	{Code: "MM", Name: "Myanmar (Birmania)", DefaultCurrency: "MMK"},
	{Code: "NA", Name: "Namibia", DefaultCurrency: "NAD"},
	{Code: "NR", Name: "Nauru", DefaultCurrency: "AUD"},
	{Code: "NP", Name: "Nepal", DefaultCurrency: "NPR"},
	{Code: "NI", Name: "Nicaragua", DefaultCurrency: "NIO"},
	{Code: "NE", Name: "Níger", DefaultCurrency: "XOF"},
	{Code: "NG", Name: "Nigeria", DefaultCurrency: "NGN"},
	{Code: "NU", Name: "Niue", DefaultCurrency: "NZD"},
	{Code: "NO", Name: "Noruega", DefaultCurrency: "NOK"},
	{Code: "NC", Name: "Nueva Caledonia", DefaultCurrency: "XPF"},
	{Code: "NZ", Name: "Nueva Zelanda", DefaultCurrency: "NZD"},
	{Code: "OM", Name: "Omán", DefaultCurrency: "OMR"},
	{Code: "NL", Name: "Países Bajos", DefaultCurrency: "EUR"},
	{Code: "PK", Name: "Pakistán", DefaultCurrency: "PKR"},
	{Code: "PW", Name: "Palaos", DefaultCurrency: "USD"},
	{Code: "PA", Name: "Panamá", DefaultCurrency: "PAB"},
	{Code: "PG", Name: "Papúa Nueva Guinea", DefaultCurrency: "PGK"},
	{Code: "PY", Name: "Paraguay", DefaultCurrency: "PYG"},
	{Code: "PE", Name: "Perú", DefaultCurrency: "PEN"},
	{Code: "PF", Name: "Polinesia Francesa", DefaultCurrency: "XPF"},
	{Code: "PL", Name: "Polonia", DefaultCurrency: "PLN"},
	{Code: "PT", Name: "Portugal", DefaultCurrency: "EUR"},
	{Code: "PR", Name: "Puerto Rico", DefaultCurrency: "USD"},
	{Code: "HK", Name: "RAE de Hong Kong (China)", DefaultCurrency: "HKD"},
	{Code: "MO", Name: "RAE de Macao (China)", DefaultCurrency: "MOP"},
	{Code: "GB", Name: "Reino Unido", DefaultCurrency: "GBP"},
	{Code: "CF", Name: "República Centroafricana", DefaultCurrency: "XAF"},
	{Code: "CD", Name: "República Democrática del Congo", DefaultCurrency: "CDF"},
	{Code: "DO", Name: "República Dominicana", DefaultCurrency: "DOP"},
	{Code: "RE", Name: "Reunión", DefaultCurrency: "EUR"},
	{Code: "RW", Name: "Ruanda", DefaultCurrency: "RWF"},
	{Code: "RO", Name: "Rumanía", DefaultCurrency: "RON"},
	{Code: "RU", Name: "Rusia", DefaultCurrency: "RUB"},
	{Code: "EH", Name: "Sáhara Occidental", DefaultCurrency: "MAD"},
	{Code: "WS", Name: "Samoa", DefaultCurrency: "WST"},
	{Code: "AS", Name: "Samoa Americana", DefaultCurrency: "USD"},
	{Code: "BL", Name: "San Bartolomé", DefaultCurrency: "EUR"},
	{Code: "KN", Name: "San Cristóbal y Nieves", DefaultCurrency: "XCD"},
	{Code: "SM", Name: "San Marino", DefaultCurrency: "EUR"},
	{Code: "MF", Name: "San Martín", DefaultCurrency: "EUR"},
	{Code: "PM", Name: "San Pedro y Miquelón", DefaultCurrency: "EUR"},
	{Code: "VC", Name: "San Vicente y las Granadinas", DefaultCurrency: "XCD"},
	{Code: "SH", Name: "Santa Elena", DefaultCurrency: "SHP"},
	{Code: "LC", Name: "Santa Lucía", DefaultCurrency: "XCD"},
	{Code: "ST", Name: "Santo Tomé y Príncipe", DefaultCurrency: "STN"},
	{Code: "SN", Name: "Senegal", DefaultCurrency: "XOF"},
	{Code: "RS", Name: "Serbia", DefaultCurrency: "RSD"},
	{Code: "SC", Name: "Seychelles", DefaultCurrency: "SCR"},
	{Code: "SL", Name: "Sierra Leona", DefaultCurrency: "SLE"},
	{Code: "SG", Name: "Singapur", DefaultCurrency: "SGD"},
	{Code: "SX", Name: "Sint Maarten", DefaultCurrency: "XCG"},
	{Code: "SY", Name: "Siria", DefaultCurrency: "SYP"},
	{Code: "SO", Name: "Somalia", DefaultCurrency: "SOS"},
	{Code: "LK", Name: "Sri Lanka", DefaultCurrency: "LKR"},
	{Code: "ZA", Name: "Sudáfrica", DefaultCurrency: "ZAR"},
	{Code: "SD", Name: "Sudán", DefaultCurrency: "SDG"},
	{Code: "SS", Name: "Sudán del Sur", DefaultCurrency: "SSP"},
	{Code: "SE", Name: "Suecia", DefaultCurrency: "SEK"},
	{Code: "CH", Name: "Suiza", DefaultCurrency: "CHF"},
	{Code: "SR", Name: "Surinam", DefaultCurrency: "SRD"},
	{Code: "SJ", Name: "Svalbard y Jan Mayen", DefaultCurrency: "NOK"},
	{Code: "TH", Name: "Tailandia", DefaultCurrency: "THB"},
	{Code: "TW", Name: "Taiwán", DefaultCurrency: "TWD"},
	{Code: "TZ", Name: "Tanzania", DefaultCurrency: "TZS"},
	{Code: "TJ", Name: "Tayikistán", DefaultCurrency: "TJS"},
	{Code: "IO", Name: "Territorio Británico del Océano Índico", DefaultCurrency: "USD"},
	{Code: "TF", Name: "Territorios Australes Franceses", DefaultCurrency: "EUR"},
	{Code: "PS", Name: "Territorios Palestinos", DefaultCurrency: "ILS"},
	{Code: "TL", Name: "Timor-Leste", DefaultCurrency: "USD"},
	{Code: "TG", Name: "Togo", DefaultCurrency: "XOF"},
	{Code: "TK", Name: "Tokelau", DefaultCurrency: "NZD"},
	{Code: "TO", Name: "Tonga", DefaultCurrency: "TOP"},
	{Code: "TT", Name: "Trinidad y Tobago", DefaultCurrency: "TTD"},
	{Code: "TA", Name: "Tristán de Acuña", DefaultCurrency: "GBP"},
	{Code: "TN", Name: "Túnez", DefaultCurrency: "TND"},
	{Code: "TM", Name: "Turkmenistán", DefaultCurrency: "TMT"},
	{Code: "TR", Name: "Turquía", DefaultCurrency: "TRY"},
	{Code: "TV", Name: "Tuvalu", DefaultCurrency: "AUD"},
	{Code: "UA", Name: "Ucrania", DefaultCurrency: "UAH"},
	{Code: "UG", Name: "Uganda", DefaultCurrency: "UGX"},
	{Code: "EU", Name: "Unión Europea", DefaultCurrency: "EUR"},
	{Code: "UY", Name: "Uruguay", DefaultCurrency: "UYU"},
	{Code: "UZ", Name: "Uzbekistán", DefaultCurrency: "UZS"},
	{Code: "VU", Name: "Vanuatu", DefaultCurrency: "VUV"},
	{Code: "VE", Name: "Venezuela", DefaultCurrency: "VES"},
	{Code: "VN", Name: "Vietnam", DefaultCurrency: "VND"},
	{Code: "WF", Name: "Wallis y Futuna", DefaultCurrency: "XPF"},
	{Code: "YE", Name: "Yemen", DefaultCurrency: "YER"},
	{Code: "DJ", Name: "Yibuti", DefaultCurrency: "DJF"},
	{Code: "ZM", Name: "Zambia", DefaultCurrency: "ZMW"},
	{Code: "ZW", Name: "Zimbabue", DefaultCurrency: "ZWG"},
}
