// Code generated from SIX ISO 4217 List One (2026-01-01); DO NOT EDIT.
package httpapi

type currencyOption struct {
	Code     string `json:"code"`
	Name     string `json:"name"`
	Symbol   string `json:"symbol"`
	Decimals int    `json:"decimals"`
}

var supportedCurrencies = []currencyOption{
	{Code: "AED", Name: "Dírham de los Emiratos Árabes Unidos", Symbol: "AED", Decimals: 2},
	{Code: "AFN", Name: "Afgani afgano", Symbol: "؋", Decimals: 2},
	{Code: "ALL", Name: "Lek albanés", Symbol: "ALL", Decimals: 2},
	{Code: "AMD", Name: "Dram armenio", Symbol: "֏", Decimals: 2},
	{Code: "AOA", Name: "Kuanza angoleño", Symbol: "Kz", Decimals: 2},
	{Code: "ARS", Name: "Peso argentino", Symbol: "$", Decimals: 2},
	{Code: "AUD", Name: "Dólar australiano", Symbol: "$", Decimals: 2},
	{Code: "AWG", Name: "Florín arubeño", Symbol: "AWG", Decimals: 2},
	{Code: "AZN", Name: "Manat azerbaiyano", Symbol: "₼", Decimals: 2},
	{Code: "BAM", Name: "Marco convertible de Bosnia y Herzegovina", Symbol: "KM", Decimals: 2},
	{Code: "BBD", Name: "Dólar barbadense", Symbol: "$", Decimals: 2},
	{Code: "BDT", Name: "Taka bangladesí", Symbol: "৳", Decimals: 2},
	{Code: "BHD", Name: "Dinar bareiní", Symbol: "BHD", Decimals: 3},
	{Code: "BIF", Name: "Franco burundés", Symbol: "BIF", Decimals: 0},
	{Code: "BMD", Name: "Dólar bermudeño", Symbol: "$", Decimals: 2},
	{Code: "BND", Name: "Dólar bruneano", Symbol: "$", Decimals: 2},
	{Code: "BOB", Name: "Boliviano", Symbol: "Bs", Decimals: 2},
	{Code: "BRL", Name: "Real brasileño", Symbol: "R$", Decimals: 2},
	{Code: "BSD", Name: "Dólar bahameño", Symbol: "$", Decimals: 2},
	{Code: "BTN", Name: "Gultrum butanés", Symbol: "BTN", Decimals: 2},
	{Code: "BWP", Name: "Pula botsuano", Symbol: "P", Decimals: 2},
	{Code: "BYN", Name: "Rublo bielorruso", Symbol: "р.", Decimals: 2},
	{Code: "BZD", Name: "Dólar beliceño", Symbol: "$", Decimals: 2},
	{Code: "CAD", Name: "Dólar canadiense", Symbol: "$", Decimals: 2},
	{Code: "CDF", Name: "Franco congoleño", Symbol: "CDF", Decimals: 2},
	{Code: "CHF", Name: "Franco suizo", Symbol: "CHF", Decimals: 2},
	{Code: "CLP", Name: "Peso chileno", Symbol: "$", Decimals: 0},
	{Code: "CNY", Name: "Yuan renminbi", Symbol: "¥", Decimals: 2},
	{Code: "COP", Name: "Peso colombiano", Symbol: "$", Decimals: 2},
	{Code: "CRC", Name: "Colón costarricense", Symbol: "₡", Decimals: 2},
	{Code: "CUP", Name: "Peso cubano", Symbol: "$", Decimals: 2},
	{Code: "CVE", Name: "Escudo de Cabo Verde", Symbol: "CVE", Decimals: 2},
	{Code: "CZK", Name: "Corona checa", Symbol: "Kč", Decimals: 2},
	{Code: "DJF", Name: "Franco yibutiano", Symbol: "DJF", Decimals: 0},
	{Code: "DKK", Name: "Corona danesa", Symbol: "kr", Decimals: 2},
	{Code: "DOP", Name: "Peso dominicano", Symbol: "$", Decimals: 2},
	{Code: "DZD", Name: "Dinar argelino", Symbol: "DZD", Decimals: 2},
	{Code: "EGP", Name: "Libra egipcia", Symbol: "E£", Decimals: 2},
	{Code: "ERN", Name: "Nakfa eritreo", Symbol: "ERN", Decimals: 2},
	{Code: "ETB", Name: "Bir etíope", Symbol: "ETB", Decimals: 2},
	{Code: "EUR", Name: "Euro", Symbol: "€", Decimals: 2},
	{Code: "FJD", Name: "Dólar fiyiano", Symbol: "$", Decimals: 2},
	{Code: "FKP", Name: "Libra malvinense", Symbol: "FK£", Decimals: 2},
	{Code: "GBP", Name: "Libra esterlina", Symbol: "£", Decimals: 2},
	{Code: "GEL", Name: "Lari georgiano", Symbol: "₾", Decimals: 2},
	{Code: "GHS", Name: "Cedi ghanés", Symbol: "GH₵", Decimals: 2},
	{Code: "GIP", Name: "Libra gibraltareña", Symbol: "£", Decimals: 2},
	{Code: "GMD", Name: "Dalasi gambiano", Symbol: "GMD", Decimals: 2},
	{Code: "GNF", Name: "Franco guineano", Symbol: "FG", Decimals: 0},
	{Code: "GTQ", Name: "Quetzal guatemalteco", Symbol: "Q", Decimals: 2},
	{Code: "GYD", Name: "Dólar guyanés", Symbol: "$", Decimals: 2},
	{Code: "HKD", Name: "Dólar hongkonés", Symbol: "$", Decimals: 2},
	{Code: "HNL", Name: "Lempira hondureño", Symbol: "L", Decimals: 2},
	{Code: "HTG", Name: "Gurde haitiano", Symbol: "HTG", Decimals: 2},
	{Code: "HUF", Name: "Forinto húngaro", Symbol: "Ft", Decimals: 2},
	{Code: "IDR", Name: "Rupia indonesia", Symbol: "Rp", Decimals: 2},
	{Code: "ILS", Name: "Nuevo séquel israelí", Symbol: "₪", Decimals: 2},
	{Code: "INR", Name: "Rupia india", Symbol: "₹", Decimals: 2},
	{Code: "IQD", Name: "Dinar iraquí", Symbol: "IQD", Decimals: 3},
	{Code: "IRR", Name: "Rial iraní", Symbol: "IRR", Decimals: 2},
	{Code: "ISK", Name: "Corona islandesa", Symbol: "kr", Decimals: 0},
	{Code: "JMD", Name: "Dólar jamaicano", Symbol: "$", Decimals: 2},
	{Code: "JOD", Name: "Dinar jordano", Symbol: "JOD", Decimals: 3},
	{Code: "JPY", Name: "Yen japonés", Symbol: "¥", Decimals: 0},
	{Code: "KES", Name: "Chelín keniano", Symbol: "KES", Decimals: 2},
	{Code: "KGS", Name: "Som kirguís", Symbol: "⃀", Decimals: 2},
	{Code: "KHR", Name: "Riel camboyano", Symbol: "៛", Decimals: 2},
	{Code: "KMF", Name: "Franco comorense", Symbol: "CF", Decimals: 0},
	{Code: "KPW", Name: "Won norcoreano", Symbol: "₩", Decimals: 2},
	{Code: "KRW", Name: "Won surcoreano", Symbol: "₩", Decimals: 0},
	{Code: "KWD", Name: "Dinar kuwaití", Symbol: "KWD", Decimals: 3},
	{Code: "KYD", Name: "Dólar de las Islas Caimán", Symbol: "$", Decimals: 2},
	{Code: "KZT", Name: "Tengue kazajo", Symbol: "₸", Decimals: 2},
	{Code: "LAK", Name: "Kip laosiano", Symbol: "₭", Decimals: 2},
	{Code: "LBP", Name: "Libra libanesa", Symbol: "L£", Decimals: 2},
	{Code: "LKR", Name: "Rupia esrilanquesa", Symbol: "Rs", Decimals: 2},
	{Code: "LRD", Name: "Dólar liberiano", Symbol: "$", Decimals: 2},
	{Code: "LSL", Name: "Loti lesotense", Symbol: "LSL", Decimals: 2},
	{Code: "LYD", Name: "Dinar libio", Symbol: "LYD", Decimals: 3},
	{Code: "MAD", Name: "Dírham marroquí", Symbol: "MAD", Decimals: 2},
	{Code: "MDL", Name: "Leu moldavo", Symbol: "MDL", Decimals: 2},
	{Code: "MGA", Name: "Ariari malgache", Symbol: "Ar", Decimals: 2},
	{Code: "MKD", Name: "Dinar macedonio", Symbol: "MKD", Decimals: 2},
	{Code: "MMK", Name: "Kiat de Myanmar", Symbol: "K", Decimals: 2},
	{Code: "MNT", Name: "Tugrik mongol", Symbol: "₮", Decimals: 2},
	{Code: "MOP", Name: "Pataca macaense", Symbol: "MOP", Decimals: 2},
	{Code: "MRU", Name: "Uguiya mauritano", Symbol: "MRU", Decimals: 2},
	{Code: "MUR", Name: "Rupia mauriciana", Symbol: "Rs", Decimals: 2},
	{Code: "MVR", Name: "Rufiya maldiva", Symbol: "MVR", Decimals: 2},
	{Code: "MWK", Name: "Kuacha malauí", Symbol: "MWK", Decimals: 2},
	{Code: "MXN", Name: "Peso mexicano", Symbol: "$", Decimals: 2},
	{Code: "MYR", Name: "Ringit malasio", Symbol: "RM", Decimals: 2},
	{Code: "MZN", Name: "Metical mozambiqueño", Symbol: "MZN", Decimals: 2},
	{Code: "NAD", Name: "Dólar namibio", Symbol: "$", Decimals: 2},
	{Code: "NGN", Name: "Naira nigeriano", Symbol: "₦", Decimals: 2},
	{Code: "NIO", Name: "Córdoba oro", Symbol: "C$", Decimals: 2},
	{Code: "NOK", Name: "Corona noruega", Symbol: "kr", Decimals: 2},
	{Code: "NPR", Name: "Rupia nepalí", Symbol: "Rs", Decimals: 2},
	{Code: "NZD", Name: "Dólar neozelandés", Symbol: "$", Decimals: 2},
	{Code: "OMR", Name: "Rial omaní", Symbol: "OMR", Decimals: 3},
	{Code: "PAB", Name: "Balboa panameño", Symbol: "PAB", Decimals: 2},
	{Code: "PEN", Name: "Sol peruano", Symbol: "S/", Decimals: 2},
	{Code: "PGK", Name: "Kina papú", Symbol: "PGK", Decimals: 2},
	{Code: "PHP", Name: "Peso filipino", Symbol: "₱", Decimals: 2},
	{Code: "PKR", Name: "Rupia pakistaní", Symbol: "Rs", Decimals: 2},
	{Code: "PLN", Name: "Esloti polaco", Symbol: "zł", Decimals: 2},
	{Code: "PYG", Name: "Guaraní paraguayo", Symbol: "₲", Decimals: 0},
	{Code: "QAR", Name: "Rial catarí", Symbol: "QAR", Decimals: 2},
	{Code: "RON", Name: "Leu rumano", Symbol: "L", Decimals: 2},
	{Code: "RSD", Name: "Dinar serbio", Symbol: "RSD", Decimals: 2},
	{Code: "RUB", Name: "Rublo ruso", Symbol: "₽", Decimals: 2},
	{Code: "RWF", Name: "Franco ruandés", Symbol: "RF", Decimals: 0},
	{Code: "SAR", Name: "Rial saudí", Symbol: "SAR", Decimals: 2},
	{Code: "SBD", Name: "Dólar salomonense", Symbol: "$", Decimals: 2},
	{Code: "SCR", Name: "Rupia seychellense", Symbol: "SCR", Decimals: 2},
	{Code: "SDG", Name: "Libra sudanesa", Symbol: "SDG", Decimals: 2},
	{Code: "SEK", Name: "Corona sueca", Symbol: "kr", Decimals: 2},
	{Code: "SGD", Name: "Dólar singapurense", Symbol: "$", Decimals: 2},
	{Code: "SHP", Name: "Libra de Santa Elena", Symbol: "£", Decimals: 2},
	{Code: "SLE", Name: "Leona sierraleonesa", Symbol: "SLE", Decimals: 2},
	{Code: "SOS", Name: "Chelín somalí", Symbol: "SOS", Decimals: 2},
	{Code: "SRD", Name: "Dólar surinamés", Symbol: "$", Decimals: 2},
	{Code: "SSP", Name: "Libra sursudanesa", Symbol: "SD£", Decimals: 2},
	{Code: "STN", Name: "Dobra santotomense", Symbol: "Db", Decimals: 2},
	{Code: "SVC", Name: "Colón salvadoreño", Symbol: "SVC", Decimals: 2},
	{Code: "SYP", Name: "Libra siria", Symbol: "S£", Decimals: 2},
	{Code: "SZL", Name: "Lilangeni esuatiní", Symbol: "SZL", Decimals: 2},
	{Code: "THB", Name: "Bat tailandés", Symbol: "฿", Decimals: 2},
	{Code: "TJS", Name: "Somoni tayiko", Symbol: "TJS", Decimals: 2},
	{Code: "TMT", Name: "Manat turcomano", Symbol: "TMT", Decimals: 2},
	{Code: "TND", Name: "Dinar tunecino", Symbol: "TND", Decimals: 3},
	{Code: "TOP", Name: "Paanga tongano", Symbol: "T$", Decimals: 2},
	{Code: "TRY", Name: "Lira turca", Symbol: "₺", Decimals: 2},
	{Code: "TTD", Name: "Dólar de Trinidad y Tobago", Symbol: "$", Decimals: 2},
	{Code: "TWD", Name: "Nuevo dólar taiwanés", Symbol: "NT$", Decimals: 2},
	{Code: "TZS", Name: "Chelín tanzano", Symbol: "TZS", Decimals: 2},
	{Code: "UAH", Name: "Grivna ucraniana", Symbol: "₴", Decimals: 2},
	{Code: "UGX", Name: "Chelín ugandés", Symbol: "UGX", Decimals: 0},
	{Code: "USD", Name: "Dólar estadounidense", Symbol: "$", Decimals: 2},
	{Code: "UYU", Name: "Peso uruguayo", Symbol: "$", Decimals: 2},
	{Code: "UZS", Name: "Sum uzbeko", Symbol: "UZS", Decimals: 2},
	{Code: "VED", Name: "VED", Symbol: "VED", Decimals: 2},
	{Code: "VES", Name: "Bolívar venezolano", Symbol: "VES", Decimals: 2},
	{Code: "VND", Name: "Dong vietnamita", Symbol: "₫", Decimals: 0},
	{Code: "VUV", Name: "Vatu vanuatense", Symbol: "VUV", Decimals: 0},
	{Code: "WST", Name: "Tala samoano", Symbol: "WST", Decimals: 2},
	{Code: "XAF", Name: "Franco CFA de África Central", Symbol: "XAF", Decimals: 0},
	{Code: "XCD", Name: "Dólar del Caribe Oriental", Symbol: "$", Decimals: 2},
	{Code: "XCG", Name: "Florín caribeño", Symbol: "Cg.", Decimals: 2},
	{Code: "XOF", Name: "Franco CFA de África Occidental", Symbol: "XOF", Decimals: 0},
	{Code: "XPF", Name: "Franco CFP", Symbol: "CFPF", Decimals: 0},
	{Code: "YER", Name: "Rial yemení", Symbol: "YER", Decimals: 2},
	{Code: "ZAR", Name: "Rand sudafricano", Symbol: "R", Decimals: 2},
	{Code: "ZMW", Name: "Kuacha zambiano", Symbol: "ZK", Decimals: 2},
	{Code: "ZWG", Name: "Oro zimbabuense", Symbol: "ZWG", Decimals: 2},
}
