package httpapi

import (
	"encoding/json"
	"errors"
	"net/http"
	"strings"

	"github.com/jackc/pgx/v5"
)

type customerAddress struct { ID string `json:"id"`; Label string `json:"label"`; Address string `json:"address"`; Reference string `json:"reference"`; District string `json:"district"`; City string `json:"city"`; CountryCode string `json:"countryCode"`; Default bool `json:"default"` }
type customer struct { ID string `json:"id"`; Code string `json:"code"`; CustomerType string `json:"customerType"`; DisplayName string `json:"displayName"`; DocumentType string `json:"documentType"`; DocumentNumber string `json:"documentNumber"`; Phone string `json:"phone"`; Email string `json:"email"`; PreferredChannel string `json:"preferredChannel"`; Preferences string `json:"preferences"`; Notes string `json:"notes"`; MarketingConsent bool `json:"marketingConsent"`; VIPOverride bool `json:"vipOverride"`; VisitCount int `json:"visitCount"`; TotalSpent string `json:"totalSpent"`; LastPurchaseAt *string `json:"lastPurchaseAt"`; Active bool `json:"active"`; Segment string `json:"segment"`; Addresses []customerAddress `json:"addresses,omitempty"` }
type customerInput struct { CustomerType string `json:"customerType"`; DisplayName string `json:"displayName"`; DocumentType string `json:"documentType"`; DocumentNumber string `json:"documentNumber"`; Phone string `json:"phone"`; Email string `json:"email"`; PreferredChannel string `json:"preferredChannel"`; Preferences string `json:"preferences"`; Notes string `json:"notes"`; MarketingConsent bool `json:"marketingConsent"`; VIPOverride bool `json:"vipOverride"`; Addresses []customerAddress `json:"addresses"` }

const customerColumns = `id,code,customer_type,display_name,document_type,document_number,phone,email,preferred_channel,preferences,notes,marketing_consent,vip_override,visit_count,total_spent::text,CASE WHEN last_purchase_at IS NULL THEN NULL ELSE to_char(last_purchase_at,'YYYY-MM-DD"T"HH24:MI:SSOF') END,active,CASE WHEN vip_override THEN 'vip' WHEN visit_count>=5 THEN 'frequent' WHEN visit_count>=2 THEN 'recurrent' ELSE 'new' END`
var customerChannels=[]map[string]string{{"value":"none","label":"Sin preferencia"},{"value":"whatsapp","label":"WhatsApp"},{"value":"phone","label":"Llamada"},{"value":"email","label":"Correo electrónico"}}
var customerSegments=[]map[string]string{{"value":"new","label":"Nuevo"},{"value":"recurrent","label":"Recurrente"},{"value":"frequent","label":"Frecuente"},{"value":"vip","label":"VIP"}}
var customerTypes=[]map[string]string{{"value":"person","label":"Persona"},{"value":"company","label":"Empresa"}}
var customerDocumentTypes=[]map[string]string{{"value":"","label":"Sin documento"},{"value":"DNI","label":"DNI"},{"value":"CE","label":"Carné de extranjería"},{"value":"RUC","label":"RUC"},{"value":"PASAPORTE","label":"Pasaporte"}}

func scanCustomer(row pgx.Row)(customer,error){var c customer;err:=row.Scan(&c.ID,&c.Code,&c.CustomerType,&c.DisplayName,&c.DocumentType,&c.DocumentNumber,&c.Phone,&c.Email,&c.PreferredChannel,&c.Preferences,&c.Notes,&c.MarketingConsent,&c.VIPOverride,&c.VisitCount,&c.TotalSpent,&c.LastPurchaseAt,&c.Active,&c.Segment);return c,err}
func validCustomer(in *customerInput) bool { in.DisplayName=strings.TrimSpace(in.DisplayName); in.CustomerType=strings.TrimSpace(in.CustomerType); if in.CustomerType==""{in.CustomerType="person"}; if in.PreferredChannel==""{in.PreferredChannel="none"}; return in.DisplayName!=""&&(in.CustomerType=="person"||in.CustomerType=="company")&&(in.PreferredChannel=="none"||in.PreferredChannel=="whatsapp"||in.PreferredChannel=="phone"||in.PreferredChannel=="email") }

func (a *API) listCustomers(w http.ResponseWriter,r *http.Request){s:=r.Context().Value(scopeKey{}).(scope);page,size:=pageParams(r);q:=strings.TrimSpace(r.URL.Query().Get("q"));status:=r.URL.Query().Get("status");segment:=r.URL.Query().Get("segment");where:=`organization_id=$1 AND ($2='' OR display_name ILIKE '%'||$2||'%' OR code ILIKE '%'||$2||'%' OR phone ILIKE '%'||$2||'%' OR email ILIKE '%'||$2||'%' OR document_number ILIKE '%'||$2||'%') AND ($3='' OR ($3='active' AND active) OR ($3='inactive' AND NOT active)) AND ($4='' OR $4=CASE WHEN vip_override THEN 'vip' WHEN visit_count>=5 THEN 'frequent' WHEN visit_count>=2 THEN 'recurrent' ELSE 'new' END)`;var total int;if err:=a.db.QueryRow(r.Context(),`SELECT count(*) FROM customers WHERE `+where,s.OrganizationID,q,status,segment).Scan(&total);err!=nil{fail(w,503,"customers_unavailable","No pudimos cargar los clientes.");return};rows,err:=a.db.Query(r.Context(),`SELECT `+customerColumns+` FROM customers WHERE `+where+` ORDER BY updated_at DESC,display_name LIMIT $5 OFFSET $6`,s.OrganizationID,q,status,segment,size,(page-1)*size);if err!=nil{fail(w,503,"customers_unavailable","No pudimos cargar los clientes.");return};defer rows.Close();items:=[]customer{};for rows.Next(){c,scanErr:=scanCustomer(rows);if scanErr!=nil{fail(w,503,"customers_unavailable","No pudimos cargar los clientes.");return};items=append(items,c)};writeJSON(w,200,map[string]any{"items":items,"total":total,"page":page,"pageSize":size,"channelOptions":customerChannels,"segmentOptions":customerSegments,"customerTypeOptions":customerTypes,"documentTypeOptions":customerDocumentTypes})}
func (a *API) getCustomer(w http.ResponseWriter,r *http.Request){s:=r.Context().Value(scopeKey{}).(scope);c,err:=scanCustomer(a.db.QueryRow(r.Context(),`SELECT `+customerColumns+` FROM customers WHERE id=$1 AND organization_id=$2`,r.PathValue("id"),s.OrganizationID));if errors.Is(err,pgx.ErrNoRows){fail(w,404,"customer_not_found","El cliente no existe.");return};if err!=nil{fail(w,503,"customer_unavailable","No pudimos cargar el cliente.");return};c.Addresses=[]customerAddress{};rows,err:=a.db.Query(r.Context(),`SELECT id,label,address,reference,district,city,country_code,is_default FROM customer_addresses WHERE customer_id=$1 AND organization_id=$2 AND active ORDER BY is_default DESC,created_at`,c.ID,s.OrganizationID);if err==nil{defer rows.Close();for rows.Next(){var ad customerAddress;if rows.Scan(&ad.ID,&ad.Label,&ad.Address,&ad.Reference,&ad.District,&ad.City,&ad.CountryCode,&ad.Default)==nil{c.Addresses=append(c.Addresses,ad)}}};writeJSON(w,200,c)}
func (a *API) createCustomer(w http.ResponseWriter,r *http.Request){a.saveCustomer(w,r,false)}
func (a *API) updateCustomer(w http.ResponseWriter,r *http.Request){a.saveCustomer(w,r,true)}
func (a *API) saveCustomer(w http.ResponseWriter,r *http.Request,updating bool){s:=r.Context().Value(scopeKey{}).(scope);var in customerInput;if json.NewDecoder(r.Body).Decode(&in)!=nil||!validCustomer(&in){fail(w,400,"invalid_customer","El nombre y los datos del cliente no son válidos.");return};tx,err:=a.db.Begin(r.Context());if err!=nil{fail(w,503,"customer_unavailable","No pudimos guardar el cliente.");return};defer tx.Rollback(r.Context());var c customer;if updating{c,err=scanCustomer(tx.QueryRow(r.Context(),`UPDATE customers SET customer_type=$3,display_name=$4,document_type=$5,document_number=$6,phone=$7,email=$8,preferred_channel=$9,preferences=$10,notes=$11,marketing_consent=$12,vip_override=$13,updated_at=now() WHERE id=$1 AND organization_id=$2 RETURNING `+customerColumns,r.PathValue("id"),s.OrganizationID,in.CustomerType,in.DisplayName,strings.TrimSpace(in.DocumentType),strings.TrimSpace(in.DocumentNumber),strings.TrimSpace(in.Phone),strings.TrimSpace(in.Email),in.PreferredChannel,strings.TrimSpace(in.Preferences),strings.TrimSpace(in.Notes),in.MarketingConsent,in.VIPOverride))}else{c,err=scanCustomer(tx.QueryRow(r.Context(),`INSERT INTO customers(organization_id,customer_type,display_name,document_type,document_number,phone,email,preferred_channel,preferences,notes,marketing_consent,vip_override) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING `+customerColumns,s.OrganizationID,in.CustomerType,in.DisplayName,strings.TrimSpace(in.DocumentType),strings.TrimSpace(in.DocumentNumber),strings.TrimSpace(in.Phone),strings.TrimSpace(in.Email),in.PreferredChannel,strings.TrimSpace(in.Preferences),strings.TrimSpace(in.Notes),in.MarketingConsent,in.VIPOverride))};if err!=nil{if errors.Is(err,pgx.ErrNoRows){fail(w,404,"customer_not_found","El cliente no existe.")}else{fail(w,409,"customer_conflict","Ya existe un cliente con ese documento o los datos no son válidos.")};return};if updating{if _,err=tx.Exec(r.Context(),`DELETE FROM customer_addresses WHERE customer_id=$1 AND organization_id=$2`,c.ID,s.OrganizationID);err!=nil{fail(w,503,"customer_unavailable","No pudimos guardar las direcciones.");return}};for _,ad:=range in.Addresses{if strings.TrimSpace(ad.Address)==""{continue};if ad.Label==""{ad.Label="Principal"};if ad.CountryCode==""{ad.CountryCode="PE"};_,err=tx.Exec(r.Context(),`INSERT INTO customer_addresses(organization_id,customer_id,label,address,reference,district,city,country_code,is_default) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,s.OrganizationID,c.ID,ad.Label,ad.Address,ad.Reference,ad.District,ad.City,strings.ToUpper(ad.CountryCode),ad.Default);if err!=nil{fail(w,400,"invalid_address","Revisa las direcciones del cliente.");return}};if err=tx.Commit(r.Context());err!=nil{fail(w,503,"customer_unavailable","No pudimos guardar el cliente.");return};a.audit(r,map[bool]string{true:"updated",false:"created"}[updating],"customer",c.ID);writeJSON(w,map[bool]int{true:200,false:201}[updating],c)}
func (a *API) updateCustomerStatus(w http.ResponseWriter,r *http.Request){s:=r.Context().Value(scopeKey{}).(scope);var in struct{Active bool `json:"active"`};if json.NewDecoder(r.Body).Decode(&in)!=nil{fail(w,400,"invalid_status","El estado no es válido.");return};tag,err:=a.db.Exec(r.Context(),`UPDATE customers SET active=$3,updated_at=now() WHERE id=$1 AND organization_id=$2`,r.PathValue("id"),s.OrganizationID,in.Active);if err!=nil||tag.RowsAffected()==0{fail(w,404,"customer_not_found","El cliente no existe.");return};a.audit(r,"status_updated","customer",r.PathValue("id"));w.WriteHeader(http.StatusNoContent)}
