import {ButtonHTMLAttributes,forwardRef,InputHTMLAttributes,SelectHTMLAttributes,TextareaHTMLAttributes} from "react";
import {Icon,IconName} from "@/design-system/icons";

type ButtonProps=ButtonHTMLAttributes<HTMLButtonElement>&{icon?:IconName;kind?:"primary"|"secondary"|"ghost"|"danger"|"success"};
export function Button({children,icon,kind="primary",type="button",className="",...props}:ButtonProps){return <button type={type} className={`button ${kind} ${className}`.trim()} {...props}>{icon&&<Icon name={icon} size={18}/>}<span>{children}</span></button>}
export function IconButton({icon,label,className="",type="button",...props}:{icon:IconName;label:string}&Omit<ButtonHTMLAttributes<HTMLButtonElement>,"aria-label">){return <button type={type} className={`ds-icon-button ${className}`.trim()} aria-label={label} data-tooltip={label} {...props}><Icon name={icon} size={18}/></button>}
type RowAction="view"|"edit"|"activate"|"deactivate"|"remove";
const rowActions:Record<RowAction,{icon:IconName;label:string;tone:"default"|"danger"}>={view:{icon:"eye",label:"Ver detalle",tone:"default"},edit:{icon:"edit",label:"Editar",tone:"default"},activate:{icon:"power",label:"Activar",tone:"default"},deactivate:{icon:"power",label:"Desactivar",tone:"danger"},remove:{icon:"close",label:"Quitar fila",tone:"danger"}};
export function RowActionButton({action,label,className="",...props}:{action:RowAction;label?:string}&Omit<ButtonHTMLAttributes<HTMLButtonElement>,"aria-label">){const definition=rowActions[action];return <IconButton icon={definition.icon} label={label??definition.label} className={`${definition.tone==="danger"?"danger":""} ${className}`.trim()} {...props}/>}
export function FieldLabel({children,hint}:{children:React.ReactNode;hint:string}){return <span className="field-label">{children}<i className="field-hint" data-tooltip={hint} tabIndex={0} role="note" aria-label={hint}>i</i></span>}
export const Input=forwardRef<HTMLInputElement,InputHTMLAttributes<HTMLInputElement>>(function Input({className="",...props},ref){return <input ref={ref} className={`ds-input ${className}`.trim()} {...props}/>});
export const Select=forwardRef<HTMLSelectElement,SelectHTMLAttributes<HTMLSelectElement>>(function Select({className="",children,...props},ref){return <select ref={ref} className={`ds-select ${className}`.trim()} {...props}>{children}</select>});
export const Textarea=forwardRef<HTMLTextAreaElement,TextareaHTMLAttributes<HTMLTextAreaElement>>(function Textarea({className="",...props},ref){return <textarea ref={ref} className={`ds-textarea ${className}`.trim()} {...props}/>});
export function PageHeader({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:React.ReactNode}){return <header className="page-header"><div><small>{eyebrow}</small><h1>{title}</h1><p>{description}</p></div>{action}</header>}
export function Status({tone="green",children}:{tone?:"green"|"blue"|"orange"|"gray";children:React.ReactNode}){return <span className={`status ${tone}`}><i/>{children}</span>}
export function Pagination({page,size,total,onPage,onSize}:{page:number;size:number;total:number;onPage:(page:number)=>void;onSize:(size:number)=>void}){
 const last=Math.max(1,Math.ceil(total/size));const safePage=Math.min(Math.max(page,1),last);const pages=paginationItems(safePage,last);const start=total?(safePage-1)*size+1:0;const end=Math.min(safePage*size,total);
 return <footer className="standard-pagination"><span>{total?`Mostrando ${start}–${end} de ${total}`:"Sin resultados"}</span><label>Filas <Select value={size} onChange={event=>onSize(Number(event.target.value))}><option>10</option><option>20</option><option>50</option></Select></label><nav aria-label="Paginación"><button type="button" className="pagination-nav" disabled={safePage<=1} onClick={()=>onPage(safePage-1)}><Icon name="chevronLeft" size={14}/><span>Anterior</span></button>{pages.map((value,index)=>value==="ellipsis"?<span className="pagination-ellipsis" aria-hidden="true" key={`ellipsis-${index}`}>…</span>:<button type="button" className={`pagination-page${value===safePage?" active":""}`} aria-label={`Página ${value}`} aria-current={value===safePage?"page":undefined} onClick={()=>onPage(value)} key={value}>{value}</button>)}<button type="button" className="pagination-nav" disabled={safePage>=last} onClick={()=>onPage(safePage+1)}><span>Siguiente</span><Icon name="chevron" size={14}/></button></nav></footer>
}
function paginationItems(page:number,total:number):(number|"ellipsis")[]{if(total<=5)return Array.from({length:total},(_,index)=>index+1);const values=new Set([1,total,page-1,page,page+1].filter(value=>value>=1&&value<=total));const sorted=[...values].sort((a,b)=>a-b);const result:(number|"ellipsis")[]=[];sorted.forEach((value,index)=>{if(index&&value-sorted[index-1]>1)result.push("ellipsis");result.push(value)});return result}
export function Toolbar({placeholder="Buscar..."}:{placeholder?:string}){return <div className="toolbar"><label><Icon name="search" size={18}/><input placeholder={placeholder}/></label><button><Icon name="filter" size={17}/>Filtros</button><button><Icon name="download" size={17}/>Exportar</button></div>}
