"use client";
import "./product-wizard.css";
import {useRef,useState} from "react";
import AsyncSelect from "react-select/async";
import type {StylesConfig} from "react-select";
import {Icon} from "@/design-system/icons";
import {RichTextEditor} from "@/design-system/rich-text-editor";
import type {Category,ProductDraft} from "../domain/types";

type AllergenOption={label:string;value:string};
const selectStyles:StylesConfig<AllergenOption,true>={control:(base)=>({...base,height:"var(--control-height)",minHeight:"var(--control-height)",borderColor:"#e4e7ec",borderRadius:"6px",fontSize:"11px",fontWeight:600,boxShadow:"none",outline:"none","&:hover":{borderColor:"#d0d5dd"}}),valueContainer:(base)=>({...base,padding:"0 10px",height:"var(--control-height)"}),multiValue:(base)=>({...base,backgroundColor:"var(--ops-100)",borderRadius:"4px",margin:"2px"}),multiValueLabel:(base)=>({...base,color:"var(--ops-700)",fontSize:"10px",fontWeight:600,padding:"2px 6px"}),multiValueRemove:(base)=>({...base,color:"var(--ops-700)",borderRadius:"4px",padding:0,width:"18px","&:hover":{backgroundColor:"var(--danger)",color:"#fff"}}),option:(base,state)=>({...base,fontSize:"11px",fontWeight:600,backgroundColor:state.isSelected?"var(--ops-500)":state.isFocused?"var(--ops-100)":"transparent",color:state.isSelected?"#fff":"var(--ink-700)",cursor:"pointer",padding:"6px 10px"}),menu:(base)=>({...base,zIndex:5,fontSize:"11px",border:"1px solid #e4e7ec",borderRadius:"6px",boxShadow:"0 4px 12px #1018281a"}),input:(base)=>({...base,fontSize:"11px",fontWeight:600,margin:0,padding:0,border:"none",outline:"none",boxShadow:"none",background:"transparent",opacity:1}),placeholder:(base)=>({...base,fontSize:"11px",fontWeight:400,color:"#98a2b3",margin:0,textAlign:"left"}),indicatorSeparator:(base)=>({...base,display:"none"}),dropdownIndicator:(base)=>({...base,padding:"0 8px"})};

export function ProductDialog({draft,categories,loadAllergens,currencySymbol,busy,close,save}:{draft:ProductDraft;categories:Category[];loadAllergens:(q:string)=>Promise<AllergenOption[]>;currencySymbol:string;busy:boolean;close:()=>void;save:(d:ProductDraft,f:File|null)=>void}){
 const[value,setValue]=useState(draft);const[attempted,setAttempted]=useState(false);const[showExtras,setShowExtras]=useState(Boolean(draft.prepMinutes)||draft.allergens.length>0||draft.featured);const[pendingFile,setPendingFile]=useState<File|null>(null);const[previewUrl,setPreviewUrl]=useState<string|null>(draft.imageUrl);const fileRef=useRef<HTMLInputElement>(null);
 const priceValid=/^[0-9]+([.][0-9]{1,2})?$/.test(value.price);
 const inventoryLocked=Boolean(draft.id)&&draft.quantityControl==="inventory";
 const valid=value.name.trim().length>0&&priceValid;
 function selectFile(file:File){setPendingFile(file);setPreviewUrl(URL.createObjectURL(file))}
 function clearImage(){setPendingFile(null);setPreviewUrl(null);setValue({...value,imageUrl:null})}
 function submit(event:React.FormEvent){event.preventDefault();setAttempted(true);if(!valid)return;save(value,pendingFile)}
 return <div className="modal-backdrop modal-overlay-in" role="presentation"><section className="crud-modal product-form modal-panel-in" role="dialog" aria-modal="true" aria-labelledby="product-title" aria-busy={busy}><div className="modal-accent"/><header><span className="modal-title-icon"><Icon name="box" size={18}/></span><div><small>{value.id?"EDITAR PRODUCTO":"NUEVO PRODUCTO"}</small><h2 id="product-title">Información del producto</h2></div><button onClick={close} disabled={busy} aria-label="Cerrar"><Icon name="close"/></button></header><form onSubmit={submit} noValidate><div className="product-form-body"><div className="form-grid">
  <label className="span-2">Nombre del producto<input autoFocus required maxLength={160} aria-invalid={attempted&&!value.name.trim()} value={value.name} onChange={e=>setValue({...value,name:e.target.value})} placeholder="Ej. Lomo saltado"/>{attempted&&!value.name.trim()&&<small className="wizard-field-error">Ingresa el nombre del producto.</small>}</label>
  <label>Precio de venta<div className="money-input"><span>{currencySymbol}</span><input required inputMode="decimal" aria-invalid={attempted&&!priceValid} value={value.price} onChange={e=>setValue({...value,price:e.target.value})} placeholder="0.00"/></div>{attempted&&!priceValid&&<small className="wizard-field-error">Ingresa un precio válido.</small>}</label>
  <label>Categoría<select value={value.categoryId} onChange={e=>setValue({...value,categoryId:e.target.value})}><option value="">Sin categoría</option>{categories.filter(c=>(c.active||c.id===value.categoryId)&&(c.id===value.categoryId||c.productScope==="both"||c.productScope===value.productType)).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label>
  <fieldset className="product-stock-mode span-2"><legend>Control de cantidad <small>{inventoryLocked?"Gestionado desde Inventario":"Define de dónde sale la existencia"}</small></legend>{inventoryLocked?<div className="product-stock-locked"><span><Icon name="stock" size={16}/></span><b>Inventario físico<small>Las entradas y existencias se administran desde Inventario. Aquí solo editas la información comercial.</small></b></div>:<><div className="product-stock-options is-two"><label><input className="product-radio" type="radio" name="quantityControl" value="none" checked={value.quantityControl==="none"} onChange={()=>setValue({...value,quantityControl:"none"})}/><b>Sin control<small>Para productos cuya venta no depende de una cantidad.</small></b></label><label><input className="product-radio" type="radio" name="quantityControl" value="portions" checked={value.quantityControl==="portions"} onChange={()=>setValue({...value,quantityControl:"portions"})}/><b>Porciones preparadas<small>Las porciones disponibles se cargan cada día en Disponibilidad de la carta.</small></b></label></div></>}</fieldset>
  <label className="product-description span-2">Descripción<RichTextEditor value={value.description} onChange={html=>setValue({...value,description:html})} placeholder="Ingredientes, presentación o información útil para el equipo"/></label>
  <label className="product-image span-2">Imagen del producto (opcional)<input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={e=>{const file=e.target.files?.[0];if(file)selectFile(file)}}/><div className="image-drop" onClick={()=>fileRef.current?.click()} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==="Enter"||e.key===" ")fileRef.current?.click()}}>{previewUrl?<><img src={previewUrl} alt={value.name}/><button type="button" className="image-clear" disabled={busy} onClick={e=>{e.stopPropagation();clearImage()}} aria-label="Quitar imagen"><Icon name="close" size={16}/></button></>:<div className="image-drop-empty"><Icon name="box" size={24}/><span>Seleccionar imagen</span><small>PNG, JPEG o WebP · máximo 5 MB</small></div>}</div></label>
 </div><button type="button" className={showExtras?"product-extras-toggle open":"product-extras-toggle"} onClick={()=>setShowExtras(!showExtras)} aria-expanded={showExtras}><Icon name="chevron" size={16}/><b>Información adicional</b><small>Opcional</small></button>{showExtras&&<div className="form-grid product-extras"><label>Tiempo de preparación (min)<input type="number" min="0" inputMode="numeric" value={value.prepMinutes} onChange={e=>setValue({...value,prepMinutes:e.target.value})} placeholder="Ej. 15"/></label><label>Precio de costo (opcional)<div className="money-input"><span>{currencySymbol}</span><input inputMode="decimal" pattern="[0-9]+([.][0-9]{1,2})?" value={value.costPrice} onChange={e=>setValue({...value,costPrice:e.target.value})} placeholder="0.00"/></div></label><label className="span-2">Alérgenos<AsyncSelect isMulti cacheOptions loadOptions={loadAllergens} defaultOptions={false} placeholder="Escribir para buscar alérgenos..." value={value.allergens.map(a=>({label:a,value:a}))} onChange={items=>setValue({...value,allergens:items.map(option=>option.value)})} styles={selectStyles} className="react-select-container" classNamePrefix="rs" noOptionsMessage={()=>value.allergens.length?"No hay más coincidencias":"Escribe para buscar"}/></label><label className="switch-row compact span-2"><input type="checkbox" checked={value.featured} onChange={e=>setValue({...value,featured:e.target.checked})}/><span/><b>Plato destacado</b></label></div>}</div><footer><button type="button" className="button ghost" onClick={close} disabled={busy}>Cancelar</button><button className="button primary" disabled={busy}>{busy?"Guardando…":"Guardar"}</button></footer></form>{busy&&<div className="modal-busy" role="status"><i/><span>Guardando…</span></div>}</section></div>
}
