"use client";
/* eslint-disable @next/next/no-img-element -- Local blob previews must bypass Next image optimization. */
import {Dialog} from "@/design-system/dialog";
import "./product-wizard.css";
import {useRef,useState} from "react";
import {Controller,useForm} from "react-hook-form";
import AsyncSelect from "react-select/async";
import type {StylesConfig} from "react-select";
import {FormField,Input,Select} from "@/design-system";
import {Icon} from "@/design-system/icons";
import {RichTextEditor} from "@/design-system/rich-text-editor";
import type {Category,ProductDraft,ServiceDestinationOption} from "../domain/types";
import {productResolver} from "../domain/product-schema";

type AllergenOption={label:string;value:string};
const selectStyles:StylesConfig<AllergenOption,true>={control:(base)=>({...base,height:"var(--control-height)",minHeight:"var(--control-height)",borderColor:"var(--line)",borderRadius:"var(--radius-control)",fontSize:"var(--font-size-control)",fontWeight:"var(--font-weight-600)",boxShadow:"none",outline:"none","&:hover":{borderColor:"var(--palette-blue-26)"}}),valueContainer:(base)=>({...base,padding:"0 var(--space-10)",height:"var(--control-height)"}),multiValue:(base)=>({...base,backgroundColor:"var(--ops-100)",borderRadius:"var(--radius-4)",margin:"var(--space-2)"}),multiValueLabel:(base)=>({...base,color:"var(--ops-700)",fontSize:"var(--font-size-label)",fontWeight:"var(--font-weight-600)",padding:"var(--space-2) var(--space-6)"}),multiValueRemove:(base)=>({...base,color:"var(--ops-700)",borderRadius:"var(--radius-4)",padding:0,width:"var(--size-18)","&:hover":{backgroundColor:"var(--danger)",color:"var(--surface)"}}),option:(base,state)=>({...base,fontSize:"var(--font-size-control)",fontWeight:"var(--font-weight-600)",backgroundColor:state.isSelected?"var(--ops-500)":state.isFocused?"var(--ops-100)":"transparent",color:state.isSelected?"#fff":"var(--ink-700)",cursor:"pointer",padding:"var(--space-6) var(--space-10)"}),menu:(base)=>({...base,zIndex:5,fontSize:"var(--font-size-control)",border:"var(--stroke-1) solid var(--line)",borderRadius:"var(--radius-control)",boxShadow:"var(--shadow-104)"}),input:(base)=>({...base,fontSize:"var(--font-size-control)",fontWeight:"var(--font-weight-600)",margin:0,padding:0,border:"none",outline:"none",boxShadow:"none",background:"transparent",opacity:1}),placeholder:(base)=>({...base,fontSize:"var(--font-size-control)",fontWeight:"var(--font-weight-400)",color:"var(--ink-400)",margin:0,textAlign:"left"}),indicatorSeparator:(base)=>({...base,display:"none"}),dropdownIndicator:(base)=>({...base,padding:"0 var(--space-8)"})};

export function ProductDialog({draft,categories,destinations,loadAllergens,currencySymbol,busy,close,save}:{draft:ProductDraft;categories:Category[];destinations:ServiceDestinationOption[];loadAllergens:(q:string)=>Promise<AllergenOption[]>;currencySymbol:string;busy:boolean;close:()=>void;save:(d:ProductDraft,f:File|null)=>Promise<void>}){
 const[showExtras,setShowExtras]=useState(Boolean(draft.prepMinutes)||draft.allergens.length>0||draft.featured);const[pendingFile,setPendingFile]=useState<File|null>(null);const[previewUrl,setPreviewUrl]=useState<string|null>(draft.imageUrl);const fileRef=useRef<HTMLInputElement>(null);
 const{register,control,watch,setValue,handleSubmit,formState:{errors}}=useForm<ProductDraft>({defaultValues:{...draft,serviceDestination:draft.serviceDestination??"kitchen"},resolver:productResolver,mode:"onSubmit",reValidateMode:"onChange"});
 const submitting=useRef(false);
 const value=watch();
 const inventoryLocked=Boolean(draft.id)&&draft.quantityControl==="inventory";
 function selectFile(file:File){setPendingFile(file);setPreviewUrl(URL.createObjectURL(file))}
 function clearImage(){setPendingFile(null);setPreviewUrl(null);setValue("imageUrl",null)}
 // Lock before async validation so rapid activations cannot queue duplicate requests.
 async function submit(){
  if(busy||submitting.current)return;
  submitting.current=true;
  try{await handleSubmit(values=>save(values,pendingFile))()}
  finally{submitting.current=false}
 }
 return <div className="modal-backdrop modal-overlay-in" role="presentation"><Dialog className="crud-modal product-form modal-panel-in" role="dialog" aria-modal="true" aria-labelledby="product-title" aria-busy={busy}><div className="modal-accent"/><header><span className="modal-title-icon"><Icon name="box" size={18}/></span><div><small>{draft.id?"EDITAR PRODUCTO":"NUEVO PRODUCTO"}</small><h2 id="product-title">Información del producto</h2></div><button onClick={close} disabled={busy} aria-label="Cerrar"><Icon name="close"/></button></header><form onSubmit={event=>event.preventDefault()} noValidate><div className="product-form-body"><div className="form-grid">
  <FormField className="span-2" label="Nombre del producto" error={errors.name?.message}><Input autoFocus maxLength={160} {...register("name")} placeholder="Ej. Lomo saltado"/></FormField>
  <FormField label="Precio de venta" error={errors.price?.message}><div className={"money-input"+(errors.price?" has-error":"")}><span>{currencySymbol}</span><input inputMode="decimal" {...register("price")} placeholder="0.00" aria-invalid={Boolean(errors.price)}/></div></FormField>
  <FormField label="Categoría"><Select {...register("categoryId")}><option value="">Sin categoría</option>{categories.filter(c=>(c.active||c.id===value.categoryId)&&(c.id===value.categoryId||c.productScope==="both"||c.productScope===value.productType)).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</Select></FormField>
  <FormField className="span-2" label="Destino de atención" error={errors.serviceDestination?.message}><Select disabled={busy||!destinations.length} {...register("serviceDestination")}>{destinations.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</Select></FormField>
  <fieldset className="product-stock-mode span-2"><legend>Control de cantidad <small>{inventoryLocked?"Gestionado desde Inventario":"Define de dónde sale la existencia"}</small></legend>{inventoryLocked?<div className="product-stock-locked"><span><Icon name="stock" size={16}/></span><b>Inventario físico<small>Las entradas y existencias se administran desde Inventario. Aquí solo editas la información comercial.</small></b></div>:<div className="product-stock-options is-two"><label><input className="product-radio" type="radio" value="none" {...register("quantityControl")}/><b>Sin control<small>Para productos cuya venta no depende de una cantidad.</small></b></label><label><input className="product-radio" type="radio" value="portions" {...register("quantityControl")}/><b>Porciones preparadas<small>Las porciones disponibles se cargan cada día en Disponibilidad de la carta.</small></b></label></div>}</fieldset>
  <FormField as="div" className="product-description span-2" label="Descripción"><Controller control={control} name="description" render={({field})=><RichTextEditor value={field.value} onChange={field.onChange} placeholder="Ingredientes, presentación o información útil para el equipo"/>}/></FormField>
  <FormField as="div" className="product-image span-2" label="Imagen del producto" optional help="PNG, JPEG o WebP · máximo 5 MB"><><input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={e=>{const file=e.target.files?.[0];if(file)selectFile(file)}}/><div className="image-drop" onClick={()=>fileRef.current?.click()} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==="Enter"||e.key===" ")fileRef.current?.click()}}>{previewUrl?<><img src={previewUrl} alt={value.name}/><button type="button" className="image-clear" disabled={busy} onClick={e=>{e.stopPropagation();clearImage()}} aria-label="Quitar imagen"><Icon name="close" size={16}/></button></>:<div className="image-drop-empty"><Icon name="box" size={24}/><span>Seleccionar imagen</span></div>}</div></></FormField>
 </div><button type="button" className={showExtras?"product-extras-toggle open":"product-extras-toggle"} onClick={()=>setShowExtras(!showExtras)} aria-expanded={showExtras}><Icon name="chevron" size={16}/><b>Información adicional</b><small>Opcional</small></button>{showExtras&&<div className="form-grid product-extras"><FormField label="Tiempo de preparación (min)" error={errors.prepMinutes?.message}><Input type="number" min="0" inputMode="numeric" {...register("prepMinutes")} placeholder="Ej. 15"/></FormField><FormField label="Precio de costo" optional error={errors.costPrice?.message}><div className={"money-input"+(errors.costPrice?" has-error":"")}><span>{currencySymbol}</span><input inputMode="decimal" {...register("costPrice")} placeholder="0.00" aria-invalid={Boolean(errors.costPrice)}/></div></FormField><FormField as="div" className="span-2" label="Alérgenos"><Controller control={control} name="allergens" render={({field})=><AsyncSelect isMulti cacheOptions loadOptions={loadAllergens} defaultOptions={false} placeholder="Escribir para buscar alérgenos..." value={field.value.map(a=>({label:a,value:a}))} onChange={items=>field.onChange(items.map(option=>option.value))} styles={selectStyles} className="react-select-container" classNamePrefix="rs" noOptionsMessage={()=>field.value.length?"No hay más coincidencias":"Escribe para buscar"}/>}/></FormField><label className="switch-row compact span-2"><input type="checkbox" {...register("featured")}/><span/><b>Plato destacado</b></label></div>}</div><footer><button type="button" className="button ghost" onClick={close} disabled={busy}>Cancelar</button><button type="button" className="button primary" onClick={()=>void submit()} disabled={busy}>{busy?"Guardando…":"Guardar"}</button></footer></form>{busy&&<div className="modal-busy" role="status"><i/><span>Guardando…</span></div>}</Dialog></div>
}
