CREATE TABLE platform_currencies (
 code char(3) PRIMARY KEY CHECK (code ~ '^[A-Z]{3}$'), name text NOT NULL, symbol text NOT NULL,
 decimals smallint NOT NULL CHECK (decimals BETWEEN 0 AND 4), active boolean NOT NULL DEFAULT true,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE platform_countries (
 code char(2) PRIMARY KEY CHECK (code ~ '^[A-Z]{2}$'), name text NOT NULL,
 default_currency char(3) NOT NULL REFERENCES platform_currencies(code), active boolean NOT NULL DEFAULT true,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE platform_whatsapp_channels (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), country_code char(2) NOT NULL REFERENCES platform_countries(code),
 phone_number text NOT NULL UNIQUE, phone_number_id text NOT NULL UNIQUE, display_name text,
 secret_ref text, active boolean NOT NULL DEFAULT true,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 CHECK (length(btrim(phone_number)) > 0), CHECK (length(btrim(phone_number_id)) > 0)
);
CREATE INDEX platform_whatsapp_channels_country_active_idx ON platform_whatsapp_channels(country_code,active);
INSERT INTO platform_currencies(code,name,symbol,decimals) VALUES
('AED','Dírham de los Emiratos Árabes Unidos','AED',2),
('AFN','Afgani afgano','؋',2),
('ALL','Lek albanés','ALL',2),
('AMD','Dram armenio','֏',2),
('AOA','Kuanza angoleño','Kz',2),
('ARS','Peso argentino','$',2),
('AUD','Dólar australiano','$',2),
('AWG','Florín arubeño','AWG',2),
('AZN','Manat azerbaiyano','₼',2),
('BAM','Marco convertible de Bosnia y Herzegovina','KM',2),
('BBD','Dólar barbadense','$',2),
('BDT','Taka bangladesí','৳',2),
('BHD','Dinar bareiní','BHD',3),
('BIF','Franco burundés','BIF',0),
('BMD','Dólar bermudeño','$',2),
('BND','Dólar bruneano','$',2),
('BOB','Boliviano','Bs',2),
('BRL','Real brasileño','R$',2),
('BSD','Dólar bahameño','$',2),
('BTN','Gultrum butanés','BTN',2),
('BWP','Pula botsuano','P',2),
('BYN','Rublo bielorruso','р.',2),
('BZD','Dólar beliceño','$',2),
('CAD','Dólar canadiense','$',2),
('CDF','Franco congoleño','CDF',2),
('CHF','Franco suizo','CHF',2),
('CLP','Peso chileno','$',0),
('CNY','Yuan renminbi','¥',2),
('COP','Peso colombiano','$',2),
('CRC','Colón costarricense','₡',2),
('CUP','Peso cubano','$',2),
('CVE','Escudo de Cabo Verde','CVE',2),
('CZK','Corona checa','Kč',2),
('DJF','Franco yibutiano','DJF',0),
('DKK','Corona danesa','kr',2),
('DOP','Peso dominicano','$',2),
('DZD','Dinar argelino','DZD',2),
('EGP','Libra egipcia','E£',2),
('ERN','Nakfa eritreo','ERN',2),
('ETB','Bir etíope','ETB',2),
('EUR','Euro','€',2),
('FJD','Dólar fiyiano','$',2),
('FKP','Libra malvinense','FK£',2),
('GBP','Libra esterlina','£',2),
('GEL','Lari georgiano','₾',2),
('GHS','Cedi ghanés','GH₵',2),
('GIP','Libra gibraltareña','£',2),
('GMD','Dalasi gambiano','GMD',2),
('GNF','Franco guineano','FG',0),
('GTQ','Quetzal guatemalteco','Q',2),
('GYD','Dólar guyanés','$',2),
('HKD','Dólar hongkonés','$',2),
('HNL','Lempira hondureño','L',2),
('HTG','Gurde haitiano','HTG',2),
('HUF','Forinto húngaro','Ft',2),
('IDR','Rupia indonesia','Rp',2),
('ILS','Nuevo séquel israelí','₪',2),
('INR','Rupia india','₹',2),
('IQD','Dinar iraquí','IQD',3),
('IRR','Rial iraní','IRR',2),
('ISK','Corona islandesa','kr',0),
('JMD','Dólar jamaicano','$',2),
('JOD','Dinar jordano','JOD',3),
('JPY','Yen japonés','¥',0),
('KES','Chelín keniano','KES',2),
('KGS','Som kirguís','⃀',2),
('KHR','Riel camboyano','៛',2),
('KMF','Franco comorense','CF',0),
('KPW','Won norcoreano','₩',2),
('KRW','Won surcoreano','₩',0),
('KWD','Dinar kuwaití','KWD',3),
('KYD','Dólar de las Islas Caimán','$',2),
('KZT','Tengue kazajo','₸',2),
('LAK','Kip laosiano','₭',2),
('LBP','Libra libanesa','L£',2),
('LKR','Rupia esrilanquesa','Rs',2),
('LRD','Dólar liberiano','$',2),
('LSL','Loti lesotense','LSL',2),
('LYD','Dinar libio','LYD',3),
('MAD','Dírham marroquí','MAD',2),
('MDL','Leu moldavo','MDL',2),
('MGA','Ariari malgache','Ar',2),
('MKD','Dinar macedonio','MKD',2),
('MMK','Kiat de Myanmar','K',2),
('MNT','Tugrik mongol','₮',2),
('MOP','Pataca macaense','MOP',2),
('MRU','Uguiya mauritano','MRU',2),
('MUR','Rupia mauriciana','Rs',2),
('MVR','Rufiya maldiva','MVR',2),
('MWK','Kuacha malauí','MWK',2),
('MXN','Peso mexicano','$',2),
('MYR','Ringit malasio','RM',2),
('MZN','Metical mozambiqueño','MZN',2),
('NAD','Dólar namibio','$',2),
('NGN','Naira nigeriano','₦',2),
('NIO','Córdoba oro','C$',2),
('NOK','Corona noruega','kr',2),
('NPR','Rupia nepalí','Rs',2),
('NZD','Dólar neozelandés','$',2),
('OMR','Rial omaní','OMR',3),
('PAB','Balboa panameño','PAB',2),
('PEN','Sol peruano','S/',2),
('PGK','Kina papú','PGK',2),
('PHP','Peso filipino','₱',2),
('PKR','Rupia pakistaní','Rs',2),
('PLN','Esloti polaco','zł',2),
('PYG','Guaraní paraguayo','₲',0),
('QAR','Rial catarí','QAR',2),
('RON','Leu rumano','L',2),
('RSD','Dinar serbio','RSD',2),
('RUB','Rublo ruso','₽',2),
('RWF','Franco ruandés','RF',0),
('SAR','Rial saudí','SAR',2),
('SBD','Dólar salomonense','$',2),
('SCR','Rupia seychellense','SCR',2),
('SDG','Libra sudanesa','SDG',2),
('SEK','Corona sueca','kr',2),
('SGD','Dólar singapurense','$',2),
('SHP','Libra de Santa Elena','£',2),
('SLE','Leona sierraleonesa','SLE',2),
('SOS','Chelín somalí','SOS',2),
('SRD','Dólar surinamés','$',2),
('SSP','Libra sursudanesa','SD£',2),
('STN','Dobra santotomense','Db',2),
('SVC','Colón salvadoreño','SVC',2),
('SYP','Libra siria','S£',2),
('SZL','Lilangeni esuatiní','SZL',2),
('THB','Bat tailandés','฿',2),
('TJS','Somoni tayiko','TJS',2),
('TMT','Manat turcomano','TMT',2),
('TND','Dinar tunecino','TND',3),
('TOP','Paanga tongano','T$',2),
('TRY','Lira turca','₺',2),
('TTD','Dólar de Trinidad y Tobago','$',2),
('TWD','Nuevo dólar taiwanés','NT$',2),
('TZS','Chelín tanzano','TZS',2),
('UAH','Grivna ucraniana','₴',2),
('UGX','Chelín ugandés','UGX',0),
('USD','Dólar estadounidense','$',2),
('UYU','Peso uruguayo','$',2),
('UZS','Sum uzbeko','UZS',2),
('VED','VED','VED',2),
('VES','Bolívar venezolano','VES',2),
('VND','Dong vietnamita','₫',0),
('VUV','Vatu vanuatense','VUV',0),
('WST','Tala samoano','WST',2),
('XAF','Franco CFA de África Central','XAF',0),
('XCD','Dólar del Caribe Oriental','$',2),
('XCG','Florín caribeño','Cg.',2),
('XOF','Franco CFA de África Occidental','XOF',0),
('XPF','Franco CFP','CFPF',0),
('YER','Rial yemení','YER',2),
('ZAR','Rand sudafricano','R',2),
('ZMW','Kuacha zambiano','ZK',2),
('ZWG','Oro zimbabuense','ZWG',2);
INSERT INTO platform_countries(code,name,default_currency) VALUES
('AF','Afganistán','AFN'),
('AL','Albania','ALL'),
('DE','Alemania','EUR'),
('AD','Andorra','EUR'),
('AO','Angola','AOA'),
('AI','Anguila','XCD'),
('AG','Antigua y Barbuda','XCD'),
('SA','Arabia Saudí','SAR'),
('DZ','Argelia','DZD'),
('AR','Argentina','ARS'),
('AM','Armenia','AMD'),
('AW','Aruba','AWG'),
('AU','Australia','AUD'),
('AT','Austria','EUR'),
('AZ','Azerbaiyán','AZN'),
('BS','Bahamas','BSD'),
('BD','Bangladés','BDT'),
('BB','Barbados','BBD'),
('BH','Baréin','BHD'),
('BE','Bélgica','EUR'),
('BZ','Belice','BZD'),
('BJ','Benín','XOF'),
('BM','Bermudas','BMD'),
('BY','Bielorrusia','BYN'),
('BO','Bolivia','BOB'),
('BA','Bosnia y Herzegovina','BAM'),
('BW','Botsuana','BWP'),
('BR','Brasil','BRL'),
('BN','Brunéi','BND'),
('BG','Bulgaria','EUR'),
('BF','Burkina Faso','XOF'),
('BI','Burundi','BIF'),
('BT','Bután','BTN'),
('CV','Cabo Verde','CVE'),
('KH','Camboya','KHR'),
('CM','Camerún','XAF'),
('CA','Canadá','CAD'),
('IC','Canarias','EUR'),
('BQ','Caribe neerlandés','USD'),
('QA','Catar','QAR'),
('EA','Ceuta y Melilla','EUR'),
('TD','Chad','XAF'),
('CZ','Chequia','CZK'),
('CL','Chile','CLP'),
('CN','China','CNY'),
('CY','Chipre','EUR'),
('VA','Ciudad del Vaticano','EUR'),
('CO','Colombia','COP'),
('KM','Comoras','KMF'),
('CG','Congo','XAF'),
('KP','Corea del Norte','KPW'),
('KR','Corea del Sur','KRW'),
('CR','Costa Rica','CRC'),
('CI','Côte d’Ivoire','XOF'),
('HR','Croacia','EUR'),
('CU','Cuba','CUP'),
('CW','Curazao','XCG'),
('DG','Diego García','USD'),
('DK','Dinamarca','DKK'),
('DM','Dominica','XCD'),
('EC','Ecuador','USD'),
('EG','Egipto','EGP'),
('SV','El Salvador','USD'),
('AE','Emiratos Árabes Unidos','AED'),
('ER','Eritrea','ERN'),
('SK','Eslovaquia','EUR'),
('SI','Eslovenia','EUR'),
('ES','España','EUR'),
('US','Estados Unidos','USD'),
('EE','Estonia','EUR'),
('SZ','Esuatini','SZL'),
('ET','Etiopía','ETB'),
('PH','Filipinas','PHP'),
('FI','Finlandia','EUR'),
('FJ','Fiyi','FJD'),
('FR','Francia','EUR'),
('GA','Gabón','XAF'),
('GM','Gambia','GMD'),
('GE','Georgia','GEL'),
('GH','Ghana','GHS'),
('GI','Gibraltar','GIP'),
('GD','Granada','XCD'),
('GR','Grecia','EUR'),
('GL','Groenlandia','DKK'),
('GP','Guadalupe','EUR'),
('GU','Guam','USD'),
('GT','Guatemala','GTQ'),
('GF','Guayana Francesa','EUR'),
('GG','Guernesey','GBP'),
('GN','Guinea','GNF'),
('GQ','Guinea Ecuatorial','XAF'),
('GW','Guinea-Bisáu','XOF'),
('GY','Guyana','GYD'),
('HT','Haití','HTG'),
('HN','Honduras','HNL'),
('HU','Hungría','HUF'),
('IN','India','INR'),
('ID','Indonesia','IDR'),
('IQ','Irak','IQD'),
('IR','Irán','IRR'),
('IE','Irlanda','EUR'),
('BV','Isla Bouvet','NOK'),
('AC','Isla de la Ascensión','SHP'),
('IM','Isla de Man','GBP'),
('CX','Isla de Navidad','AUD'),
('NF','Isla Norfolk','AUD'),
('IS','Islandia','ISK'),
('AX','Islas Aland','EUR'),
('KY','Islas Caimán','KYD'),
('CC','Islas Cocos','AUD'),
('CK','Islas Cook','NZD'),
('FO','Islas Feroe','DKK'),
('GS','Islas Georgia del Sur y Sandwich del Sur','GBP'),
('HM','Islas Heard y McDonald','AUD'),
('FK','Islas Malvinas','FKP'),
('MP','Islas Marianas del Norte','USD'),
('MH','Islas Marshall','USD'),
('UM','Islas menores alejadas de EE. UU.','USD'),
('PN','Islas Pitcairn','NZD'),
('SB','Islas Salomón','SBD'),
('TC','Islas Turcas y Caicos','USD'),
('VG','Islas Vírgenes Británicas','USD'),
('VI','Islas Vírgenes de EE. UU.','USD'),
('IL','Israel','ILS'),
('IT','Italia','EUR'),
('JM','Jamaica','JMD'),
('JP','Japón','JPY'),
('JE','Jersey','GBP'),
('JO','Jordania','JOD'),
('KZ','Kazajistán','KZT'),
('KE','Kenia','KES'),
('KG','Kirguistán','KGS'),
('KI','Kiribati','AUD'),
('XK','Kosovo','EUR'),
('KW','Kuwait','KWD'),
('LA','Laos','LAK'),
('LS','Lesoto','ZAR'),
('LV','Letonia','EUR'),
('LB','Líbano','LBP'),
('LR','Liberia','LRD'),
('LY','Libia','LYD'),
('LI','Liechtenstein','CHF'),
('LT','Lituania','EUR'),
('LU','Luxemburgo','EUR'),
('MK','Macedonia del Norte','MKD'),
('MG','Madagascar','MGA'),
('MY','Malasia','MYR'),
('MW','Malaui','MWK'),
('MV','Maldivas','MVR'),
('ML','Mali','XOF'),
('MT','Malta','EUR'),
('MA','Marruecos','MAD'),
('MQ','Martinica','EUR'),
('MU','Mauricio','MUR'),
('MR','Mauritania','MRU'),
('YT','Mayotte','EUR'),
('MX','México','MXN'),
('FM','Micronesia','USD'),
('MD','Moldavia','MDL'),
('MC','Mónaco','EUR'),
('MN','Mongolia','MNT'),
('ME','Montenegro','EUR'),
('MS','Montserrat','XCD'),
('MZ','Mozambique','MZN'),
('MM','Myanmar (Birmania)','MMK'),
('NA','Namibia','NAD'),
('NR','Nauru','AUD'),
('NP','Nepal','NPR'),
('NI','Nicaragua','NIO'),
('NE','Níger','XOF'),
('NG','Nigeria','NGN'),
('NU','Niue','NZD'),
('NO','Noruega','NOK'),
('NC','Nueva Caledonia','XPF'),
('NZ','Nueva Zelanda','NZD'),
('OM','Omán','OMR'),
('NL','Países Bajos','EUR'),
('PK','Pakistán','PKR'),
('PW','Palaos','USD'),
('PA','Panamá','PAB'),
('PG','Papúa Nueva Guinea','PGK'),
('PY','Paraguay','PYG'),
('PE','Perú','PEN'),
('PF','Polinesia Francesa','XPF'),
('PL','Polonia','PLN'),
('PT','Portugal','EUR'),
('PR','Puerto Rico','USD'),
('HK','RAE de Hong Kong (China)','HKD'),
('MO','RAE de Macao (China)','MOP'),
('GB','Reino Unido','GBP'),
('CF','República Centroafricana','XAF'),
('CD','República Democrática del Congo','CDF'),
('DO','República Dominicana','DOP'),
('RE','Reunión','EUR'),
('RW','Ruanda','RWF'),
('RO','Rumanía','RON'),
('RU','Rusia','RUB'),
('EH','Sáhara Occidental','MAD'),
('WS','Samoa','WST'),
('AS','Samoa Americana','USD'),
('BL','San Bartolomé','EUR'),
('KN','San Cristóbal y Nieves','XCD'),
('SM','San Marino','EUR'),
('MF','San Martín','EUR'),
('PM','San Pedro y Miquelón','EUR'),
('VC','San Vicente y las Granadinas','XCD'),
('SH','Santa Elena','SHP'),
('LC','Santa Lucía','XCD'),
('ST','Santo Tomé y Príncipe','STN'),
('SN','Senegal','XOF'),
('RS','Serbia','RSD'),
('SC','Seychelles','SCR'),
('SL','Sierra Leona','SLE'),
('SG','Singapur','SGD'),
('SX','Sint Maarten','XCG'),
('SY','Siria','SYP'),
('SO','Somalia','SOS'),
('LK','Sri Lanka','LKR'),
('ZA','Sudáfrica','ZAR'),
('SD','Sudán','SDG'),
('SS','Sudán del Sur','SSP'),
('SE','Suecia','SEK'),
('CH','Suiza','CHF'),
('SR','Surinam','SRD'),
('SJ','Svalbard y Jan Mayen','NOK'),
('TH','Tailandia','THB'),
('TW','Taiwán','TWD'),
('TZ','Tanzania','TZS'),
('TJ','Tayikistán','TJS'),
('IO','Territorio Británico del Océano Índico','USD'),
('TF','Territorios Australes Franceses','EUR'),
('PS','Territorios Palestinos','ILS'),
('TL','Timor-Leste','USD'),
('TG','Togo','XOF'),
('TK','Tokelau','NZD'),
('TO','Tonga','TOP'),
('TT','Trinidad y Tobago','TTD'),
('TA','Tristán de Acuña','GBP'),
('TN','Túnez','TND'),
('TM','Turkmenistán','TMT'),
('TR','Turquía','TRY'),
('TV','Tuvalu','AUD'),
('UA','Ucrania','UAH'),
('UG','Uganda','UGX'),
('EU','Unión Europea','EUR'),
('UY','Uruguay','UYU'),
('UZ','Uzbekistán','UZS'),
('VU','Vanuatu','VUV'),
('VE','Venezuela','VES'),
('VN','Vietnam','VND'),
('WF','Wallis y Futuna','XPF'),
('YE','Yemen','YER'),
('DJ','Yibuti','DJF'),
('ZM','Zambia','ZMW'),
('ZW','Zimbabue','ZWG');
