import {cashReportFormat,cashMovementSource} from "../domain/report-format";
import type {CashShiftReport} from "../domain/types";

export function CashReportContent({report}:{report:CashShiftReport}){
 const f=cashReportFormat(report),shift=report.shift;
 const expenses=shift.movements?.filter(item=>item.movementType==="expense")??[];
 const incomes=shift.movements?.filter(item=>item.movementType==="income"&&item.sourceType!=="cash_sale")??[];
 return <section className="cash-report-content" aria-label="Resumen detallado del turno">
  <dl className="cash-report-identity"><div><dt>Empresa / local</dt><dd>{report.organizationName} · {report.locationName}</dd></div><div><dt>Encargado de caja</dt><dd>{shift.openedByName}</dd></div><div><dt>Caja / turno</dt><dd>{shift.cashRegisterName} · {shift.code}</dd></div><div><dt>Día operativo</dt><dd>{f.day(shift.businessDate)}</dd></div><div><dt>Apertura</dt><dd><time dateTime={shift.openedAt}>{f.date(shift.openedAt)}</time></dd></div>{shift.closedAt&&<><div><dt>Cierre</dt><dd><time dateTime={shift.closedAt}>{f.date(shift.closedAt)}</time></dd></div><div><dt>Cerrado por</dt><dd>{shift.closedByName}</dd></div></>}</dl>
  <dl className="cash-report-amounts"><div><dt>Cobrado en el turno</dt><dd>{f.money(report.collectedAmount)}</dd></div><div><dt>Egresos de efectivo</dt><dd>{f.money(shift.expenseAmount)}</dd></div><div><dt>Efectivo esperado</dt><dd>{f.money(shift.closingExpectedAmount??shift.expectedAmount)}</dd></div></dl>
  <details className="cash-report-section" open><summary>Productos vendidos <span>{report.sales.length} líneas</span></summary><p>Detalle de los pedidos con cobros en este turno. En pagos parciales, el valor de los productos no equivale al importe cobrado.</p>
   <ReportTable headers={["Fecha y hora","Pedido / mesa","Producto","Cantidad","Precio unitario","Importe"]} empty="No hay productos de pedidos cobrados en este turno.">{report.sales.map(item=><tr key={item.id}><td><time dateTime={item.createdAt}>{f.date(item.createdAt)}</time></td><td><b>{item.orderCode}</b><small>{item.customer}</small>{item.waiterName&&<small>Mozo: {item.waiterName}</small>}</td><td><b>{item.name}</b>{item.details&&<small>{item.details}</small>}</td><td>{f.quantity(item.quantity)}</td><td>{f.money(item.unitPrice)}</td><td>{f.money(item.total)}</td></tr>)}</ReportTable>
  </details>
  <details className="cash-report-section"><summary>Cobros y medios de pago <span>{report.payments.length}</span></summary><div className="cash-report-methods">{report.methods.map((item,index)=><span key={index}>{item.name}: <b>{f.money(item.amount)}</b></span>)}</div><ReportTable headers={["Fecha y hora","Pedido","Medio de pago","Referencia","Cobrado por","Importe"]} empty="No se registraron cobros.">{report.payments.map(item=><tr key={item.id}><td>{f.date(item.createdAt)}</td><td>{item.orderCode}</td><td>{item.methodName}</td><td>{item.reference||"—"}</td><td>{item.createdByName}</td><td>{f.money(item.amount)}</td></tr>)}</ReportTable></details>
  <details className="cash-report-section"><summary>Egresos de efectivo <span>{expenses.length}</span></summary><ReportTable headers={["Fecha y hora","Origen","Motivo / detalle","Registrado por","Importe"]} empty="No se registraron egresos de efectivo.">{expenses.map(item=><tr key={item.id}><td>{f.date(item.createdAt)}</td><td>{cashMovementSource(item.sourceType)}</td><td><b>{item.reason}</b>{item.note&&<small>{item.note}</small>}</td><td>{item.createdByName}</td><td>{f.money(item.amount)}</td></tr>)}</ReportTable></details>
  <details className="cash-report-section"><summary>Otros ingresos de efectivo <span>{incomes.length}</span></summary><ReportTable headers={["Fecha y hora","Origen","Motivo / detalle","Registrado por","Importe"]} empty="No se registraron otros ingresos.">{incomes.map(item=><tr key={item.id}><td>{f.date(item.createdAt)}</td><td>{cashMovementSource(item.sourceType)}</td><td><b>{item.reason}</b>{item.note&&<small>{item.note}</small>}</td><td>{item.createdByName}</td><td>{f.money(item.amount)}</td></tr>)}</ReportTable></details>
  {report.refunds.length>0&&<details className="cash-report-section"><summary>Reversos de cobros <span>{report.refunds.length}</span></summary><ReportTable headers={["Fecha y hora","Pedido","Medio de pago","Motivo","Registrado por","Importe"]} empty="Sin reversos.">{report.refunds.map(item=><tr key={item.id}><td>{f.date(item.createdAt)}</td><td>{item.orderCode}</td><td>{item.methodName}</td><td>{item.reference}</td><td>{item.createdByName}</td><td>{f.money(item.amount)}</td></tr>)}</ReportTable></details>}
  <details className="cash-report-section"><summary>Arqueo de efectivo</summary><dl className="cash-report-amounts"><div><dt>Fondo inicial</dt><dd>{f.money(shift.openingAmount)}</dd></div><div><dt>Ingresos de efectivo</dt><dd>{f.money(shift.incomeAmount)}</dd></div><div><dt>Egresos de efectivo</dt><dd>{f.money(shift.expenseAmount)}</dd></div><div><dt>Efectivo esperado</dt><dd>{f.money(shift.closingExpectedAmount??shift.expectedAmount)}</dd></div><div><dt>Efectivo contado</dt><dd>{f.money(shift.closingCountedAmount)}</dd></div><div><dt>Diferencia</dt><dd>{f.money(shift.varianceAmount)}</dd></div></dl>{report.counts.length>0&&<ReportTable headers={["Denominación","Cantidad","Importe"]} empty="Sin conteo por denominaciones.">{report.counts.map(item=><tr key={item.denomination}><td>{f.money(item.denomination)}</td><td>{item.quantity}</td><td>{f.money(item.total)}</td></tr>)}</ReportTable>}</details>
  {(shift.openingNote||shift.closingNote)&&<dl className="cash-report-identity">{shift.openingNote&&<div><dt>Observación de apertura</dt><dd>{shift.openingNote}</dd></div>}{shift.closingNote&&<div><dt>Observación de cierre</dt><dd>{shift.closingNote}</dd></div>}</dl>}
 </section>;
}

function ReportTable({headers,children,empty}:{headers:string[];children:React.ReactNode[];empty:string}){
 return children.length?<div className="table-wrap hover-scroll cash-report-table"><table><thead><tr>{headers.map(item=><th key={item}>{item}</th>)}</tr></thead><tbody>{children}</tbody></table></div>:<p className="cash-report-empty">{empty}</p>;
}
