import type { Metadata } from "next";
import { Geist_Mono, Manrope } from "next/font/google";
import "./globals.css";
import "./organization-admin.css";
import "./onboarding.css";
import "./product-wizard.css";
import "./product-availability.css";
import "./combo-wizard.css";
import "./combo-rules.css";
import "./navigation-state.css";
import "./loading.css";
import "./table-actions.css";
import "./login.css";
import "./account-menu.css";
import "./pagination.css";
import "./settings-fiscal-states.css";
import "./table-qr.css";
import "./context-switcher.css";
import "./rich-text-editor.css";
import "./mesa-public.css";
import "./customers.css";
import "./customers-button-fix.css";
import "./users-roles.css";
import "./roles-table.css";
import "./role-editor.css";
import "./role-editor-refinement.css";
import "./orders.css";
import {Providers} from "@/providers/providers";
const manrope=Manrope({subsets:["latin"],variable:"--font-manrope"});
const geistMono=Geist_Mono({subsets:["latin"],variable:"--font-geist-mono"});
export const metadata:Metadata={title:"fudIA Admin",description:"Administración integral de restaurantes"};
export default function RootLayout({children}:{children:React.ReactNode}){return <html lang="es" suppressHydrationWarning><body className={`${manrope.variable} ${geistMono.variable}`}><Providers>{children}</Providers></body></html>}
