"use client";
import "./expenses.css";
import {useState} from "react";
import {useForm} from "react-hook-form";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {Button,ConfirmDialog,Icon,Input,PageHeader,Pagination,RowActionButton,Select,Status,Textarea} from "@/design-system";
import {useFeedback,useSession,useSettings} from "@/providers";
import {useDebouncedValue} from "@/shared/hooks/use-debounced-value";
import {formatRegionalCalendarDate,formatRegionalDateTime,formatRegionalNumber} from "@/shared/i18n/regional-format";
import type {Expense,ExpenseCategory,ExpenseDraft,ExpensePaymentMethod,ExpenseTab} from "../domain/expense";
import {expenseResolver} from "../domain/expense-schema";
import {createExpense,listExpenseCategories,listExpenses,saveExpenseCategory,setExpenseCategoryActive,voidExpense} from "../infrastructure/expenses-api";

function todayLocal(){const now=new Date();return new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,10)}
const emptyDraft=(paymentMethod=""):ExpenseDraft=>({categoryId:"",description:"",amount:"",paymentMethod,businessDate:todayLocal(),reference:"",notes:""});

export function ExpensesPage(){
 const qc=useQueryClient();const{notify}=useFeedback();const{can,location}=useSession();const settings=useSettings();
 const canManage=can("expenses.manage");const canVoid=can("expenses.void");
 const[tab,setTab]=useState<ExpenseTab>("expenses");const[q,setQ]=useState("");const debouncedQ=useDebouncedValue(q);const[status,setStatus]=useState("");const[categoryId,setCategoryId]=useState("");const[from,setFrom]=useState("");const[to,setTo]=useState("");const[page,setPage]=useState(1);const[size,setSize]=useState(10);
 const[draft,setDraft]=useState<ExpenseDraft|null>(null);const[detail,setDetail]=useState<Expense|null>(null);const[voidTarget,setVoidTarget]=useState<Expense|null>(null);const[categoryDraft,setCategoryDraft]=useState<ExpenseCategory|null|{id:"";name:string;active:true}>(null);const[categoryTarget,setCategoryTarget]=useState<ExpenseCategory|null>(null);
 const expenseList=useQuery({queryKey:["expenses",debouncedQ,categoryId,status,from,to,page,size],queryFn:()=>listExpenses({q:debouncedQ,categoryId,status,from,to,page,pageSize:size}),enabled:tab==="expenses"});
 const categories=useQuery({queryKey:["expense-categories","lookup"],queryFn:()=>listExpenseCategories({page:1,pageSize:100}),staleTime:30000});
 const categoryList=useQuery({queryKey:["expense-categories",debouncedQ,status,page,size],queryFn:()=>listExpenseCategories({q:debouncedQ,status,page,pageSize:size}),enabled:tab==="categories"});
 const create=useMutation({mutationFn:createExpense,onSuccess:item=>{setDraft(null);void qc.invalidateQueries({queryKey:["expenses"]});notify({tone:"success",title:"Gasto registrado",message:item.description+" quedó registrado por "+formatMoney(Number(item.amount),settings,location?.country)+"."})},onError:error=>notify({tone:"danger",title:"No se pudo registrar el gasto",message:error.message})});
 const voidMutation=useMutation({mutationFn:(input:{id:string;reason:string})=>voidExpense(input.id,input.reason),onSuccess:item=>{setVoidTarget(null);setDetail(item);void qc.invalidateQueries({queryKey:["expenses"]});notify({tone:"success",title:"Gasto anulado",message:"El registro se conserva con el motivo de anulación."})},onError:error=>notify({tone:"danger",title:"No se pudo anular el gasto",message:error.message})});
 const saveCategory=useMutation({mutationFn:saveExpenseCategory,onSuccess:()=>{setCategoryDraft(null);void qc.invalidateQueries({queryKey:["expense-categories"]});notify({tone:"success",title:"Categoría guardada",message:"El catálogo de gastos quedó actualizado."})},onError:error=>notify({tone:"danger",title:"No se pudo guardar la categoría",message:error.message})});
 const categoryStatus=useMutation({mutationFn:(category:ExpenseCategory)=>setExpenseCategoryActive(category.id,!category.active),onSuccess:()=>{setCategoryTarget(null);void qc.invalidateQueries({queryKey:["expense-categories"]});notify({tone:"success",title:"Estado actualizado",message:"La categoría conserva su historial."})},onError:error=>notify({tone:"danger",title:"No se pudo actualizar la categoría",message:error.message})});
 const activeCategories=(categories.data?.items??[]).filter(item=>item.active);const paymentOptions=expenseList.data?.paymentMethodOptions??[];const items=expenseList.data?.items??[];const categoryItems=categoryList.data?.items??[];
 function changeTab(next:ExpenseTab){setTab(next);setQ("");setStatus("");setCategoryId("");setFrom("");setTo("");setPage(1)}
 const headerAction=tab==="expenses"?(canManage?<Button icon="plus" onClick={()=>setDraft(emptyDraft(paymentOptions[0]?.value??""))}>Nuevo gasto</Button>:undefined):(canManage?<Button icon="plus" onClick={()=>setCategoryDraft({id:"",name:"",active:true})}>Nueva categoría</Button>:undefined);
 return <>
  <PageHeader eyebrow="INTELIGENCIA" title="Costos y gastos" description="Centraliza el control económico del local. Esta sección gestiona los gastos operativos y sus categorías." action={headerAction}/>
  <section className="panel standardized-management expenses-panel">
   <div className="expenses-tabs" role="tablist" aria-label="Gastos"><button type="button" role="tab" aria-selected={tab==="expenses"} className={tab==="expenses"?"active":""} onClick={()=>changeTab("expenses")}><Icon name="receipt" size={17}/><span>Gastos</span></button><button type="button" role="tab" aria-selected={tab==="categories"} className={tab==="categories"?"active":""} onClick={()=>changeTab("categories")}><Icon name="stock" size={17}/><span>Categorías</span></button></div>
   {tab==="expenses"?<>
    <div className="expenses-toolbar">
     <label className="expenses-search"><Icon name="search" size={18}/><Input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Buscar descripción, categoría o referencia..."/></label>
     <Select aria-label="Filtrar por categoría" value={categoryId} onChange={e=>{setCategoryId(e.target.value);setPage(1)}}><option value="">Todas las categorías</option>{(categories.data?.items??[]).map(c=><option value={c.id} key={c.id}>{c.name}{c.active?"":" · Inactiva"}</option>)}</Select>
     <Select aria-label="Filtrar por estado" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">Todos los estados</option><option value="active">Vigentes</option><option value="void">Anulados</option></Select>
     <label>Desde<Input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1)}}/></label><label>Hasta<Input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1)}}/></label>
    </div>
    {expenseList.isLoading?<Loading/>:expenseList.isError?<State title="No pudimos cargar los gastos" text={expenseList.error.message} action={()=>expenseList.refetch()}/>:!items.length?<State title={q||categoryId||status||from||to?"Sin coincidencias":"Aún no hay gastos registrados"} text={q||categoryId||status||from||to?"Ajusta los filtros para ampliar la búsqueda.":canManage?(activeCategories.length?"Registra el primer gasto operativo del local.":"Crea primero una categoría para comenzar."):"No hay gastos disponibles para este local."} action={canManage&&!q&&!categoryId&&!status&&!from&&!to?(activeCategories.length?()=>setDraft(emptyDraft(paymentOptions[0]?.value??"")):()=>{changeTab("categories");setCategoryDraft({id:"",name:"",active:true})}):undefined} actionLabel={activeCategories.length?"Nuevo gasto":"Nueva categoría"}/>:<>
     <div className="table-wrap hover-scroll expenses-table-wrap"><table><thead><tr><th>FECHA</th><th>GASTO</th><th>CATEGORÍA</th><th>MEDIO</th><th>IMPORTE</th><th>ESTADO</th><th>ACCIONES</th></tr></thead><tbody>{items.map((item,i)=><tr className={i%2?"alternate":""} key={item.id}><td><b>{formatRegionalCalendarDate(item.businessDate,location?.country,{dateStyle:"medium"})}</b><small>{formatRegionalDateTime(item.createdAt,{country:location?.country,timeZone:location?.timezone},{dateStyle:"short",timeStyle:"short"})}</small></td><td><span className={"row-icon r"+(i%3)}><Icon name="receipt" size={18}/></span><b>{item.description}</b><small>{item.reference||item.createdByName}</small></td><td>{item.categoryName}</td><td>{paymentLabel(item.paymentMethod,paymentOptions)}</td><td><b className="expense-money">{formatMoney(Number(item.amount),settings,location?.country)}</b></td><td><Status tone={item.status==="active"?"green":"gray"}>{item.status==="active"?"Vigente":"Anulado"}</Status></td><td><div className="table-actions"><RowActionButton action="view" onClick={()=>setDetail(item)}/>{canVoid&&item.status==="active"&&<RowActionButton action="remove" label="Anular gasto" onClick={()=>setVoidTarget(item)}/>}</div></td></tr>)}</tbody></table></div>
     <div className="management-cards expenses-cards">{items.map(item=><article key={item.id}><header><span className="row-icon r0"><Icon name="receipt"/></span><div><b>{item.description}</b><small>{item.categoryName}</small></div><Status tone={item.status==="active"?"green":"gray"}>{item.status==="active"?"Vigente":"Anulado"}</Status></header><dl><div><dt>Fecha</dt><dd>{formatRegionalCalendarDate(item.businessDate,location?.country,{dateStyle:"medium"})}</dd></div><div><dt>Medio</dt><dd>{paymentLabel(item.paymentMethod,paymentOptions)}</dd></div><div><dt>Importe</dt><dd>{formatMoney(Number(item.amount),settings,location?.country)}</dd></div></dl><footer><RowActionButton action="view" onClick={()=>setDetail(item)}/>{canVoid&&item.status==="active"&&<RowActionButton action="remove" label="Anular gasto" onClick={()=>setVoidTarget(item)}/>}</footer></article>)}</div>
    </>}
    {!expenseList.isLoading&&!expenseList.isError&&<Pagination page={page} size={size} total={expenseList.data?.total??0} onPage={setPage} onSize={v=>{setSize(v);setPage(1)}}/>}
   </>:<>
    <div className="expenses-toolbar category-toolbar"><label className="expenses-search"><Icon name="search" size={18}/><Input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Buscar categoría..."/></label><Select aria-label="Filtrar categorías por estado" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">Todos los estados</option><option value="active">Activas</option><option value="inactive">Inactivas</option></Select></div>
    {categoryList.isLoading?<Loading/>:categoryList.isError?<State title="No pudimos cargar las categorías" text={categoryList.error.message} action={()=>categoryList.refetch()}/>:!categoryItems.length?<State title={q||status?"Sin coincidencias":"Aún no hay categorías"} text={canManage?"Crea una categoría para clasificar los gastos operativos.":"No hay categorías disponibles."} action={canManage?()=>setCategoryDraft({id:"",name:"",active:true}):undefined} actionLabel="Nueva categoría"/>:<>
     <div className="table-wrap hover-scroll expenses-category-table"><table><thead><tr><th>CATEGORÍA</th><th>ESTADO</th><th>ACCIONES</th></tr></thead><tbody>{categoryItems.map((c,i)=><tr className={i%2?"alternate":""} key={c.id}><td><span className={"row-icon r"+(i%3)}><Icon name="stock" size={18}/></span><b>{c.name}</b></td><td><Status tone={c.active?"green":"gray"}>{c.active?"Activa":"Inactiva"}</Status></td><td><div className="table-actions">{canManage&&<><RowActionButton action="edit" onClick={()=>setCategoryDraft(c)}/><RowActionButton action={c.active?"deactivate":"activate"} onClick={()=>setCategoryTarget(c)}/></>}</div></td></tr>)}</tbody></table></div>
     <div className="management-cards expenses-cards">{categoryItems.map(c=><article key={c.id}><header><span className="row-icon r0"><Icon name="stock"/></span><div><b>{c.name}</b></div><Status tone={c.active?"green":"gray"}>{c.active?"Activa":"Inactiva"}</Status></header>{canManage&&<footer><RowActionButton action="edit" onClick={()=>setCategoryDraft(c)}/><RowActionButton action={c.active?"deactivate":"activate"} onClick={()=>setCategoryTarget(c)}/></footer>}</article>)}</div>
    </>}
    {!categoryList.isLoading&&!categoryList.isError&&<Pagination page={page} size={size} total={categoryList.data?.total??0} onPage={setPage} onSize={v=>{setSize(v);setPage(1)}}/>}
   </>}
  </section>
  {draft&&<ExpenseEditor draft={draft} categories={activeCategories} paymentOptions={paymentOptions} busy={create.isPending} currencySymbol={settings.currencySymbol} close={()=>setDraft(null)} save={value=>create.mutate(value)}/>}
  {detail&&<ExpenseDetail expense={detail} paymentLabelText={paymentLabel(detail.paymentMethod,paymentOptions)} currency={formatMoney(Number(detail.amount),settings,location?.country)} country={location?.country} timezone={location?.timezone} canVoid={canVoid} close={()=>setDetail(null)} requestVoid={()=>{setDetail(null);setVoidTarget(detail)}}/>}
  {voidTarget&&<VoidDialog expense={voidTarget} busy={voidMutation.isPending} close={()=>setVoidTarget(null)} confirm={reason=>voidMutation.mutate({id:voidTarget.id,reason})}/>}
  {categoryDraft&&<CategoryEditor category={categoryDraft} busy={saveCategory.isPending} close={()=>setCategoryDraft(null)} save={value=>saveCategory.mutate(value)}/>}
  <ConfirmDialog open={Boolean(categoryTarget)} title={categoryTarget?.active?"¿Desactivar categoría?":"¿Activar categoría?"} description={categoryTarget?.active?"Ya no podrá seleccionarse en nuevos gastos, pero el historial se conservará.":"La categoría volverá a estar disponible para nuevos gastos."} tone={categoryTarget?.active?"danger":"success"} confirmLabel={categoryTarget?.active?"Desactivar":"Activar"} pending={categoryStatus.isPending} onCancel={()=>setCategoryTarget(null)} onConfirm={()=>categoryTarget&&categoryStatus.mutate(categoryTarget)}/>
 </>;
}

function ExpenseEditor({draft,categories,paymentOptions,busy,currencySymbol,close,save}:{draft:ExpenseDraft;categories:ExpenseCategory[];paymentOptions:Array<{value:string;label:string}>;busy:boolean;currencySymbol:string;close:()=>void;save:(draft:ExpenseDraft)=>void}){
 const{register,handleSubmit,formState:{errors}}=useForm<ExpenseDraft>({defaultValues:draft,resolver:expenseResolver});
 return <div className="modal-backdrop modal-overlay-in"><section className="crud-modal expense-editor modal-panel-in" role="dialog" aria-modal="true" aria-labelledby="expense-editor-title" aria-busy={busy}><header><span className="modal-title-icon"><Icon name="receipt" size={18}/></span><div><small>GASTOS</small><h2 id="expense-editor-title">Nuevo gasto</h2></div><button type="button" aria-label="Cerrar" onClick={close} disabled={busy}><Icon name="close"/></button></header><form onSubmit={handleSubmit(save)} noValidate><div className="expense-form-grid"><label>Categoría<Select autoFocus {...register("categoryId")} aria-invalid={Boolean(errors.categoryId)}><option value="">Selecciona una categoría</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</Select>{errors.categoryId?.message&&<small className="wizard-field-error">{errors.categoryId.message}</small>}</label><label>Fecha<Input type="date" {...register("businessDate")}/></label><label className="span-2">Descripción<Input {...register("description")} placeholder="Ej. Servicio de internet del local"/>{errors.description?.message&&<small className="wizard-field-error">{errors.description.message}</small>}</label><label>Importe<div className="expense-amount-field"><span>{currencySymbol}</span><Input inputMode="decimal" {...register("amount")} placeholder="0.00"/></div>{errors.amount?.message&&<small className="wizard-field-error">{errors.amount.message}</small>}</label><label>Medio de pago<Select {...register("paymentMethod")}>{paymentOptions.map(o=><option value={o.value} key={o.value}>{o.label}</option>)}</Select></label><label className="span-2">Referencia <small>Opcional</small><Input {...register("reference")} placeholder="N.º de operación, recibo o documento"/></label><label className="span-2">Notas <small>Opcional</small><Textarea rows={3} {...register("notes")} placeholder="Información adicional para el control interno"/></label></div><footer><Button kind="ghost" onClick={close} disabled={busy}>Cancelar</Button><Button type="submit" disabled={busy}>{busy?"Guardando…":"Guardar"}</Button></footer></form></section></div>;
}

function ExpenseDetail({expense,paymentLabelText,currency,country,timezone,canVoid,close,requestVoid}:{expense:Expense;paymentLabelText:string;currency:string;country?:string|null;timezone?:string|null;canVoid:boolean;close:()=>void;requestVoid:()=>void}){
 return <div className="modal-backdrop modal-overlay-in"><section className="crud-modal expense-detail modal-panel-in" role="dialog" aria-modal="true" aria-labelledby="expense-detail-title"><header><span className="modal-title-icon"><Icon name="receipt" size={18}/></span><div><small>DETALLE DE GASTO</small><h2 id="expense-detail-title">{expense.description}</h2></div><button type="button" aria-label="Cerrar" onClick={close}><Icon name="close"/></button></header><div className="expense-detail-body"><section className="expense-detail-hero"><div><small>IMPORTE</small><b>{currency}</b></div><Status tone={expense.status==="active"?"green":"gray"}>{expense.status==="active"?"Vigente":"Anulado"}</Status></section><dl className="expense-detail-grid"><div><dt>Categoría</dt><dd>{expense.categoryName}</dd></div><div><dt>Fecha del gasto</dt><dd>{formatRegionalCalendarDate(expense.businessDate,country,{dateStyle:"medium"})}</dd></div><div><dt>Medio de pago</dt><dd>{paymentLabelText}</dd></div><div><dt>Referencia</dt><dd>{expense.reference||"Sin referencia"}</dd></div><div><dt>Registrado por</dt><dd>{expense.createdByName}</dd></div><div><dt>Registro</dt><dd>{formatRegionalDateTime(expense.createdAt,{country,timeZone:timezone},{dateStyle:"medium",timeStyle:"short"})}</dd></div><div className="span-2"><dt>Notas</dt><dd>{expense.notes||"Sin notas"}</dd></div></dl>{expense.status==="void"&&<section className="expense-void-audit"><Icon name="alert" size={18}/><div><small>ANULACIÓN</small><b>{expense.voidReason}</b><p>{expense.voidedByName}{expense.voidedAt?" · "+formatRegionalDateTime(expense.voidedAt,{country,timeZone:timezone},{dateStyle:"medium",timeStyle:"short"}):""}</p></div></section>}</div><footer><Button kind="ghost" onClick={close}>Cerrar</Button>{canVoid&&expense.status==="active"&&<Button kind="danger" icon="close" onClick={requestVoid}>Anular gasto</Button>}</footer></section></div>;
}

function VoidDialog({expense,busy,close,confirm}:{expense:Expense;busy:boolean;close:()=>void;confirm:(reason:string)=>void}){const[reason,setReason]=useState("");const valid=reason.trim().length>=4&&reason.trim().length<=240;return <div className="confirm-overlay"><section className="confirm-card expense-void-dialog" role="alertdialog" aria-modal="true" aria-labelledby="void-expense-title"><span className="confirm-icon danger"><Icon name="alert"/></span><h2 id="void-expense-title">¿Anular este gasto?</h2><p>Se conservará el registro de <b>{expense.description}</b> y quedará marcado como anulado.</p><label>Motivo de anulación<Textarea autoFocus rows={3} value={reason} maxLength={240} onChange={e=>setReason(e.target.value)} placeholder="Explica por qué se anula este registro"/></label><footer><Button kind="ghost" disabled={busy} onClick={close}>Cancelar</Button><Button kind="danger" disabled={busy||!valid} onClick={()=>confirm(reason.trim())}>{busy?"Anulando…":"Anular gasto"}</Button></footer></section></div>}

function CategoryEditor({category,busy,close,save}:{category:ExpenseCategory|{id:"";name:string;active:true};busy:boolean;close:()=>void;save:(input:{id?:string;name:string})=>void}){const[name,setName]=useState(category.name);const valid=name.trim().length>0&&name.trim().length<=100;return <div className="modal-backdrop modal-overlay-in"><section className="crud-modal expense-category-editor modal-panel-in" role="dialog" aria-modal="true" aria-labelledby="category-title"><header><span className="modal-title-icon"><Icon name="stock" size={18}/></span><div><small>GASTOS</small><h2 id="category-title">{category.id?"Editar categoría":"Nueva categoría"}</h2></div><button type="button" aria-label="Cerrar" onClick={close} disabled={busy}><Icon name="close"/></button></header><div className="expense-category-body"><label>Nombre<Input autoFocus value={name} maxLength={100} onChange={e=>setName(e.target.value)} placeholder="Ej. Servicios, limpieza, mantenimiento"/></label><p>Las categorías pertenecen a la empresa y pueden reutilizarse en cualquiera de sus locales.</p></div><footer><Button kind="ghost" onClick={close} disabled={busy}>Cancelar</Button><Button disabled={busy||!valid} onClick={()=>save({id:category.id||undefined,name:name.trim()})}>{busy?"Guardando…":"Guardar"}</Button></footer></section></div>}

function State({title,text,action,actionLabel="Nuevo gasto"}:{title:string;text:string;action?:()=>void;actionLabel?:string}){return <div className="catalog-state expenses-state"><span><Icon name="receipt"/></span><b>{title}</b><p>{text}</p>{action&&<Button kind="secondary" icon="plus" onClick={action}>{actionLabel}</Button>}</div>}
function Loading(){return <div className="expenses-loading" aria-label="Cargando gastos">{Array.from({length:6},(_,row)=><i key={row}/>)}</div>}
function paymentLabel(method:ExpensePaymentMethod,options:Array<{value:string;label:string}>){return options.find(option=>option.value===method)?.label??method}
function formatMoney(amount:number,settings:{currencySymbol:string;currencyPosition:"before"|"after";currencyDecimals:number},country?:string|null){const value=formatRegionalNumber(amount,country,{minimumFractionDigits:settings.currencyDecimals,maximumFractionDigits:settings.currencyDecimals});return settings.currencyPosition==="before"?settings.currencySymbol+" "+value:value+" "+settings.currencySymbol}
