"use client";
import {useEffect,useMemo,useState} from "react";
import {Icon} from "@/components/icon";
import {Button,Input,Label,Select} from "@/components/ui/controls";
type Status="available"|"low"|"sold_out"|"unavailable";
type Item={productId:string;name:string;categoryName:string|null;stockMode:"none"|"manual"|"linked"|"recipe";status:Status;source:string;dailyQuota:number|null;soldQuantity:number;remaining:number|null;businessDate:string};
type Response={items:Item[];businessDate:string};
const statusLabel:Record<Status,string>={available:"Disponible",low:"Pocas unidades",sold_out:"Agotado",unavailable:"Fuera de horario"};
export default function MenuPage(){
 const[data,setData]=useState<Response|null>(null);const[error,setError]=useState("");const[search,setSearch]=useState("");const[category,setCategory]=useState("");const[busy,setBusy]=useState<string|null>(null);const[quotas,setQuotas]=useState<Record<string,string>>({});
 async function load(){setError("");try{const response=await fetch("/api/operations/product-availability",{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.message??"No pudimos cargar el menú.");setData(body)}catch(reason){setError(reason instanceof Error?reason.message:"No pudimos cargar el menú.")}}
 useEffect(()=>{let active=true;fetch("/api/operations/product-availability",{cache:"no-store"}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.message??"No pudimos cargar el menú.");return body as Response}).then(body=>{if(active)setData(body)}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"No pudimos cargar el menú.")});return()=>{active=false}},[]);
 const categories=useMemo(()=>[...new Set((data?.items??[]).map(item=>item.categoryName).filter((name):name is string=>Boolean(name)))].sort(),[data]);
 const visible=(data?.items??[]).filter(item=>(!category||item.categoryName===category)&&item.name.toLowerCase().includes(search.toLowerCase()));
 async function change(item:Item,status:Exclude<Status,"unavailable">){setBusy(item.productId);setError("");try{const response=await fetch(`/api/operations/product-availability/${item.productId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,dailyQuota:item.stockMode==="manual"?Number(quotas[item.productId]??item.dailyQuota??0):null})});if(!response.ok){const body=await response.json();throw new Error(body.message??"No pudimos actualizar el plato.")}await load()}catch(reason){setError(reason instanceof Error?reason.message:"No pudimos actualizar el plato.")}finally{setBusy(null)}}
 return <div className="availability-page"><header className="availability-page-header"><div><span>OPERACIÓN DEL MENÚ</span><h1>Disponibilidad</h1><p>Actualiza el estado de los platos del local sin modificar su ficha.</p></div><div className="availability-day"><Icon name="clock" size={17}/><span><small>FECHA OPERATIVA</small><b>{data?.businessDate??"Hoy"}</b></span></div></header><section className="availability-filters"><Label><Icon name="search" size={17}/><Input placeholder="Buscar plato..." value={search} onChange={event=>setSearch(event.target.value)}/></Label><Select aria-label="Filtrar por categoría" value={category} onChange={event=>setCategory(event.target.value)}><option value="">Todas las categorías</option>{categories.map(name=><option key={name}>{name}</option>)}</Select></section>{error&&<div className="availability-error" role="alert"><Icon name="close" size={19}/><span><b>No pudimos completar la operación</b><small>{error}</small></span><Button onClick={()=>load()}>Reintentar</Button></div>}{!data&&!error?<Skeleton/>:<div className="availability-ops-grid">{visible.map(item=><article className={`availability-ops-card is-${item.status}`} key={item.productId}><header><span className="availability-food-icon"><Icon name="pos" size={20}/></span><div><b>{item.name}</b><small>{item.categoryName??"Sin categoría"}</small></div><em>{statusLabel[item.status]}</em></header><div className="availability-ops-meta"><span><small>CONTROL</small><b>{item.stockMode==="manual"?"Cupo diario":"Sin control automático"}</b></span>{item.stockMode==="manual"&&<><Label><small>CUPO DE HOY</small><Input type="number" min="0" inputMode="numeric" value={quotas[item.productId]??String(item.dailyQuota??0)} onChange={event=>setQuotas(current=>({...current,[item.productId]:event.target.value}))}/></Label><span><small>RESTANTES</small><b>{item.remaining??item.dailyQuota??0}</b></span></>}</div><footer><Button tone={item.status==="available"?"primary":"neutral"} disabled={busy===item.productId} onClick={()=>change(item,"available")}><Icon name="check" size={17}/>Disponible</Button><Button tone={item.status==="low"?"operational":"neutral"} disabled={busy===item.productId} onClick={()=>change(item,"low")}><Icon name="clock" size={17}/>Pocas</Button><Button tone="danger" disabled={busy===item.productId} onClick={()=>change(item,"sold_out")}><Icon name="close" size={17}/>Agotado</Button></footer></article>)}{data&&visible.length===0&&<div className="availability-empty"><Icon name="search" size={26}/><b>Sin resultados</b><span>Ajusta la búsqueda o la categoría.</span></div>}</div>}</div>
}
function Skeleton(){return <div className="availability-ops-grid" aria-label="Cargando disponibilidad">{Array.from({length:6},(_,index)=><article className="availability-ops-card availability-ops-skeleton" key={index}><header><i/><span/><em/></header><div><i/><i/><i/></div><footer><i/><i/><i/></footer></article>)}</div>}
