export type CategoryProductScope="prepared"|"retail"|"both";
export type Category={id:string;name:string;sortOrder:number;active:boolean;productScope:CategoryProductScope;productCount:number};
export type ServiceDestination="kitchen"|"bar"|"direct";
export type ServiceDestinationOption={value:ServiceDestination;label:string};
export type ProductType="prepared"|"retail";
export type QuantityControl="none"|"portions"|"inventory";
export type Product={
  id:string;
  sku:string;
  name:string;
  description:string;
  categoryId:string|null;
  categoryName:string|null;
  price:string;
  active:boolean;
  productType:ProductType;
  serviceDestination?:ServiceDestination;
  quantityControl:QuantityControl;
  imageUrl:string|null;
  prepMinutes:number|null;
  allergens:string[];
  featured:boolean;
  costPrice:string|null;
};
export type List<T>={items:T[];total:number;page?:number;pageSize?:number;serviceDestinationOptions?:ServiceDestinationOption[]};
export type ProductListItem=Product&{availableQuantity:number|null;inventoryUnit:string|null};
export type ProductDraft={
  id?:string;
  initialPortionQuantity?:string;
  name:string;
  description:string;
  categoryId:string;
  price:string;
  active:boolean;
  productType:ProductType;
  serviceDestination?:ServiceDestination;
  quantityControl:QuantityControl;
  imageUrl:string|null;
  prepMinutes:string;
  allergens:string[];
  featured:boolean;
  costPrice:string;
};
export type CategoryDraft={id?:string;name:string;sortOrder:number;active:boolean;productScope:CategoryProductScope};
