import type {IconName} from "@/design-system/icons";
import {pageRoutes} from "@/shared/routing/page-routes";
import type {RestaurantSetup} from "../domain/types";

export const setupPath=pageRoutes.gettingStarted;
export type SetupStep={key:string;title:string;description:string;icon:IconName;required:boolean;complete:boolean;href:string;permission:string;instructions:string[];advice:string};

export function buildSetupSteps(setup:RestaurantSetup):SetupStep[]{
  const steps:SetupStep[]=[{key:"operation",title:"Forma de atención",description:"Elige cómo recibirás los pedidos en tu restaurante.",icon:"store",required:true,complete:Boolean(setup.serviceMode),href:setupPath,permission:"organizations.manage",instructions:["Selecciona la modalidad que describe tu operación.","Si atiendes en salón, el siguiente paso te ayudará a registrar las mesas."],advice:"Puedes cambiar la modalidad más adelante. Elige la que usarás en tu primer servicio."}];
  if(setup.serviceMode==="dine_in"||setup.serviceMode==="mixed")steps.push({key:"tables",title:"Mesas y zonas",description:"Organiza los espacios donde atenderás a tus clientes.",icon:"grid",required:true,complete:setup.counts.tables>0,href:pageRoutes.tables,permission:"tables.manage",instructions:["Revisa la zona Principal o crea las zonas de tu local.","Registra el nombre, la zona y la capacidad de cada mesa."],advice:"Empieza con las mesas que estarán disponibles. Podrás ampliar el salón cuando lo necesites."});
  steps.push(
    {key:"catalog",title:"Carta inicial",description:"Prepara los platos y bebidas que ofrecerás desde el primer día.",icon:"utensils",required:true,complete:setup.counts.categories>0&&setup.counts.products>0,href:pageRoutes.products,permission:"menu.manage",instructions:["Crea las categorías que organizan tu carta.","Añade tus productos con nombre, categoría y precio.","Revisa que estén activos y disponibles para vender."],advice:"Una carta pequeña también es un buen comienzo. Puedes añadir más productos después."},
    {key:"cash",title:"Caja",description:"Prepara el lugar desde el que registrarás tus cobros.",icon:"sales",required:true,complete:setup.counts.cashRegisters>0,href:pageRoutes.cash,permission:"cash.manage",instructions:["Confirma que exista una caja activa para este local.","Al comenzar la jornada, abre un turno e indica el efectivo inicial."],advice:"La Caja principal se crea al registrar la empresa. Abre el turno cuando vayas a empezar a vender."},
    {key:"team",title:"Equipo",description:"Dale a cada persona el acceso que necesita para trabajar.",icon:"users",required:false,complete:setup.counts.users>1,href:pageRoutes.usersSettings,permission:"users.manage",instructions:["Crea los usuarios de las personas que atenderán, cocinarán o cobrarán.","Asigna a cada persona su rol y el local donde trabajará."],advice:"Puedes comenzar con tu cuenta de administrador e invitar al equipo más adelante."},
  );
  if(setup.modules.inventario)steps.push({key:"inventory",title:"Inventario",description:"Registra tus insumos y las existencias con las que comenzarás.",icon:"stock",required:false,complete:setup.counts.inventoryItems>0,href:pageRoutes.inventory,permission:"inventory.manage",instructions:["Registra los insumos o productos que necesitas controlar.","Define la unidad de medida de cada artículo.","Carga las existencias iniciales del local."],advice:"Empieza por los artículos de mayor rotación. Este paso es opcional para comenzar a atender."});
  if(setup.modules.recetas&&setup.modules.inventario)steps.push({key:"recipes",title:"Recetas",description:"Relaciona tus platos con los insumos que consumes al prepararlos.",icon:"cookingPot",required:false,complete:setup.counts.recipes>0,href:pageRoutes.recipes,permission:"recipes.manage",instructions:["Selecciona el producto preparado y su rendimiento.","Agrega sus insumos con las cantidades y mermas correspondientes."],advice:"Registra primero los productos de tu carta y los insumos de inventario para poder vincularlos."});
  if(setup.modules.compras)steps.push({key:"purchases",title:"Proveedores",description:"Organiza los contactos que abastecen tu restaurante.",icon:"truck",required:false,complete:setup.counts.suppliers>0,href:pageRoutes.purchases,permission:"purchases.manage",instructions:["Registra los datos y el contacto de tus proveedores.","Cuando necesites abastecerte, crea una compra y registra su recepción."],advice:"Puedes completar este paso después de abrir. No es necesario registrar una compra para empezar."});
  steps.push({key:"review",title:"Revisión final",description:"Comprueba lo esencial antes de comenzar a atender.",icon:"check",required:false,complete:Boolean(setup.completedAt&&setup.coreReady),href:setupPath,permission:"organizations.manage",instructions:[],advice:"Tu avance se actualiza con los datos registrados en cada sección."});
  return steps;
}

export function setupOverviewHref(key:string){return `${setupPath}?paso=${encodeURIComponent(key)}`}
export function setupGuideHref(step:SetupStep){return {pathname:step.href,query:{guia:"puesta-en-marcha",paso:step.key}}}
